// Generated by jextract

package com.github.tornaia.cf.win.processenv;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import jdk.incubator.foreign.*;
import jdk.incubator.foreign.MemoryLayout.PathElement;
import static jdk.incubator.foreign.CLinker.*;
class processenv_h$constants$106 extends processenv_h$constants$105 {

    /* package-private */ processenv_h$constants$106() {}
    static final int WS_E_NO_TRANSLATION_AVAILABLE() { return (int)-2143485943L; }

    static final int WS_E_SECURITY_VERIFICATION_FAILURE() { return (int)-2143485942L; }

    static final int WS_E_ADDRESS_IN_USE() { return (int)-2143485941L; }

    static final int WS_E_ADDRESS_NOT_AVAILABLE() { return (int)-2143485940L; }

    static final int WS_E_ENDPOINT_NOT_FOUND() { return (int)-2143485939L; }

    static final int WS_E_ENDPOINT_NOT_AVAILABLE() { return (int)-2143485938L; }

    static final int WS_E_ENDPOINT_FAILURE() { return (int)-2143485937L; }

    static final int WS_E_ENDPOINT_UNREACHABLE() { return (int)-2143485936L; }

    static final int WS_E_ENDPOINT_ACTION_NOT_SUPPORTED() { return (int)-2143485935L; }

    static final int WS_E_ENDPOINT_TOO_BUSY() { return (int)-2143485934L; }

    static final int WS_E_ENDPOINT_FAULT_RECEIVED() { return (int)-2143485933L; }

    static final int WS_E_ENDPOINT_DISCONNECTED() { return (int)-2143485932L; }

    static final int WS_E_PROXY_FAILURE() { return (int)-2143485931L; }

    static final int WS_E_PROXY_ACCESS_DENIED() { return (int)-2143485930L; }

    static final int WS_E_NOT_SUPPORTED() { return (int)-2143485929L; }

    static final int WS_E_PROXY_REQUIRES_BASIC_AUTH() { return (int)-2143485928L; }

    static final int WS_E_PROXY_REQUIRES_DIGEST_AUTH() { return (int)-2143485927L; }

    static final int WS_E_PROXY_REQUIRES_NTLM_AUTH() { return (int)-2143485926L; }

    static final int WS_E_PROXY_REQUIRES_NEGOTIATE_AUTH() { return (int)-2143485925L; }

    static final int WS_E_SERVER_REQUIRES_BASIC_AUTH() { return (int)-2143485924L; }

    static final int WS_E_SERVER_REQUIRES_DIGEST_AUTH() { return (int)-2143485923L; }

    static final int WS_E_SERVER_REQUIRES_NTLM_AUTH() { return (int)-2143485922L; }

    static final int WS_E_SERVER_REQUIRES_NEGOTIATE_AUTH() { return (int)-2143485921L; }

    static final int WS_E_INVALID_ENDPOINT_URL() { return (int)-2143485920L; }

    static final int WS_E_OTHER() { return (int)-2143485919L; }

    static final int WS_E_SECURITY_TOKEN_EXPIRED() { return (int)-2143485918L; }

    static final int WS_E_SECURITY_SYSTEM_FAILURE() { return (int)-2143485917L; }

    static final int ERROR_NDIS_INTERFACE_CLOSING() { return (int)2150891522L; }

    static final int ERROR_NDIS_BAD_VERSION() { return (int)2150891524L; }

    static final int ERROR_NDIS_BAD_CHARACTERISTICS() { return (int)2150891525L; }

    static final int ERROR_NDIS_ADAPTER_NOT_FOUND() { return (int)2150891526L; }

    static final int ERROR_NDIS_OPEN_FAILED() { return (int)2150891527L; }

    static final int ERROR_NDIS_DEVICE_FAILED() { return (int)2150891528L; }

    static final int ERROR_NDIS_MULTICAST_FULL() { return (int)2150891529L; }

    static final int ERROR_NDIS_MULTICAST_EXISTS() { return (int)2150891530L; }

    static final int ERROR_NDIS_MULTICAST_NOT_FOUND() { return (int)2150891531L; }

    static final int ERROR_NDIS_REQUEST_ABORTED() { return (int)2150891532L; }

    static final int ERROR_NDIS_RESET_IN_PROGRESS() { return (int)2150891533L; }

    static final int ERROR_NDIS_NOT_SUPPORTED() { return (int)2150891707L; }

    static final int ERROR_NDIS_INVALID_PACKET() { return (int)2150891535L; }

    static final int ERROR_NDIS_ADAPTER_NOT_READY() { return (int)2150891537L; }

    static final int ERROR_NDIS_INVALID_LENGTH() { return (int)2150891540L; }

    static final int ERROR_NDIS_INVALID_DATA() { return (int)2150891541L; }

    static final int ERROR_NDIS_BUFFER_TOO_SHORT() { return (int)2150891542L; }

    static final int ERROR_NDIS_INVALID_OID() { return (int)2150891543L; }

    static final int ERROR_NDIS_ADAPTER_REMOVED() { return (int)2150891544L; }

    static final int ERROR_NDIS_UNSUPPORTED_MEDIA() { return (int)2150891545L; }

    static final int ERROR_NDIS_GROUP_ADDRESS_IN_USE() { return (int)2150891546L; }

    static final int ERROR_NDIS_FILE_NOT_FOUND() { return (int)2150891547L; }

    static final int ERROR_NDIS_ERROR_READING_FILE() { return (int)2150891548L; }

    static final int ERROR_NDIS_ALREADY_MAPPED() { return (int)2150891549L; }

    static final int ERROR_NDIS_RESOURCE_CONFLICT() { return (int)2150891550L; }

    static final int ERROR_NDIS_MEDIA_DISCONNECTED() { return (int)2150891551L; }

    static final int ERROR_NDIS_INVALID_ADDRESS() { return (int)2150891554L; }

    static final int ERROR_NDIS_INVALID_DEVICE_REQUEST() { return (int)2150891536L; }

    static final int ERROR_NDIS_PAUSED() { return (int)2150891562L; }

    static final int ERROR_NDIS_INTERFACE_NOT_FOUND() { return (int)2150891563L; }

    static final int ERROR_NDIS_UNSUPPORTED_REVISION() { return (int)2150891564L; }

    static final int ERROR_NDIS_INVALID_PORT() { return (int)2150891565L; }

    static final int ERROR_NDIS_INVALID_PORT_STATE() { return (int)2150891566L; }

    static final int ERROR_NDIS_LOW_POWER_STATE() { return (int)2150891567L; }

    static final int ERROR_NDIS_REINIT_REQUIRED() { return (int)2150891568L; }

    static final int ERROR_NDIS_NO_QUEUES() { return (int)2150891569L; }

    static final int ERROR_NDIS_DOT11_AUTO_CONFIG_ENABLED() { return (int)2150899712L; }

    static final int ERROR_NDIS_DOT11_MEDIA_IN_USE() { return (int)2150899713L; }

    static final int ERROR_NDIS_DOT11_POWER_STATE_INVALID() { return (int)2150899714L; }

    static final int ERROR_NDIS_PM_WOL_PATTERN_LIST_FULL() { return (int)2150899715L; }

    static final int ERROR_NDIS_PM_PROTOCOL_OFFLOAD_LIST_FULL() { return (int)2150899716L; }

    static final int ERROR_NDIS_DOT11_AP_CHANNEL_CURRENTLY_NOT_AVAILABLE() { return (int)2150899717L; }

    static final int ERROR_NDIS_DOT11_AP_BAND_CURRENTLY_NOT_AVAILABLE() { return (int)2150899718L; }

    static final int ERROR_NDIS_DOT11_AP_CHANNEL_NOT_ALLOWED() { return (int)2150899719L; }

    static final int ERROR_NDIS_DOT11_AP_BAND_NOT_ALLOWED() { return (int)2150899720L; }

    static final int ERROR_NDIS_INDICATION_REQUIRED() { return (int)3407873L; }

    static final int ERROR_NDIS_OFFLOAD_POLICY() { return (int)3224637455L; }

    static final int ERROR_NDIS_OFFLOAD_CONNECTION_REJECTED() { return (int)3224637458L; }

    static final int ERROR_NDIS_OFFLOAD_PATH_REJECTED() { return (int)3224637459L; }

    static final int ERROR_HV_INVALID_HYPERCALL_CODE() { return (int)3224698882L; }

    static final int ERROR_HV_INVALID_HYPERCALL_INPUT() { return (int)3224698883L; }

    static final int ERROR_HV_INVALID_ALIGNMENT() { return (int)3224698884L; }

    static final int ERROR_HV_INVALID_PARAMETER() { return (int)3224698885L; }

    static final int ERROR_HV_ACCESS_DENIED() { return (int)3224698886L; }

    static final int ERROR_HV_INVALID_PARTITION_STATE() { return (int)3224698887L; }

    static final int ERROR_HV_OPERATION_DENIED() { return (int)3224698888L; }

    static final int ERROR_HV_UNKNOWN_PROPERTY() { return (int)3224698889L; }

    static final int ERROR_HV_PROPERTY_VALUE_OUT_OF_RANGE() { return (int)3224698890L; }

    static final int ERROR_HV_INSUFFICIENT_MEMORY() { return (int)3224698891L; }

    static final int ERROR_HV_PARTITION_TOO_DEEP() { return (int)3224698892L; }

    static final int ERROR_HV_INVALID_PARTITION_ID() { return (int)3224698893L; }

    static final int ERROR_HV_INVALID_VP_INDEX() { return (int)3224698894L; }

    static final int ERROR_HV_INVALID_PORT_ID() { return (int)3224698897L; }

    static final int ERROR_HV_INVALID_CONNECTION_ID() { return (int)3224698898L; }

    static final int ERROR_HV_INSUFFICIENT_BUFFERS() { return (int)3224698899L; }

    static final int ERROR_HV_NOT_ACKNOWLEDGED() { return (int)3224698900L; }

    static final int ERROR_HV_INVALID_VP_STATE() { return (int)3224698901L; }

    static final int ERROR_HV_ACKNOWLEDGED() { return (int)3224698902L; }

    static final int ERROR_HV_INVALID_SAVE_RESTORE_STATE() { return (int)3224698903L; }

    static final int ERROR_HV_INVALID_SYNIC_STATE() { return (int)3224698904L; }

    static final int ERROR_HV_OBJECT_IN_USE() { return (int)3224698905L; }

    static final int ERROR_HV_INVALID_PROXIMITY_DOMAIN_INFO() { return (int)3224698906L; }

    static final int ERROR_HV_NO_DATA() { return (int)3224698907L; }

    static final int ERROR_HV_INACTIVE() { return (int)3224698908L; }

    static final int ERROR_HV_NO_RESOURCES() { return (int)3224698909L; }

    static final int ERROR_HV_FEATURE_UNAVAILABLE() { return (int)3224698910L; }

    static final int ERROR_HV_INSUFFICIENT_BUFFER() { return (int)3224698931L; }

    static final int ERROR_HV_INSUFFICIENT_DEVICE_DOMAINS() { return (int)3224698936L; }

    static final int ERROR_HV_CPUID_FEATURE_VALIDATION() { return (int)3224698940L; }

    static final int ERROR_HV_CPUID_XSAVE_FEATURE_VALIDATION() { return (int)3224698941L; }

    static final int ERROR_HV_PROCESSOR_STARTUP_TIMEOUT() { return (int)3224698942L; }

    static final int ERROR_HV_SMX_ENABLED() { return (int)3224698943L; }

    static final int ERROR_HV_INVALID_LP_INDEX() { return (int)3224698945L; }

    static final int ERROR_HV_INVALID_REGISTER_VALUE() { return (int)3224698960L; }

    static final int ERROR_HV_INVALID_VTL_STATE() { return (int)3224698961L; }

    static final int ERROR_HV_NX_NOT_DETECTED() { return (int)3224698965L; }

    static final int ERROR_HV_INVALID_DEVICE_ID() { return (int)3224698967L; }

    static final int ERROR_HV_INVALID_DEVICE_STATE() { return (int)3224698968L; }

    static final int ERROR_HV_PENDING_PAGE_REQUESTS() { return (int)3473497L; }

    static final int ERROR_HV_PAGE_REQUEST_INVALID() { return (int)3224698976L; }

    static final int ERROR_HV_INVALID_CPU_GROUP_ID() { return (int)3224698991L; }

    static final int ERROR_HV_INVALID_CPU_GROUP_STATE() { return (int)3224698992L; }

    static final int ERROR_HV_OPERATION_FAILED() { return (int)3224698993L; }

    static final int ERROR_HV_NOT_ALLOWED_WITH_NESTED_VIRT_ACTIVE() { return (int)3224698994L; }

    static final int ERROR_HV_INSUFFICIENT_ROOT_MEMORY() { return (int)3224698995L; }

    static final int ERROR_HV_EVENT_BUFFER_ALREADY_FREED() { return (int)3224698996L; }

    static final int ERROR_HV_INSUFFICIENT_CONTIGUOUS_MEMORY() { return (int)3224698997L; }

    static final int ERROR_HV_NOT_PRESENT() { return (int)3224702976L; }

    static final int ERROR_VID_DUPLICATE_HANDLER() { return (int)3224829953L; }

    static final int ERROR_VID_TOO_MANY_HANDLERS() { return (int)3224829954L; }

    static final int ERROR_VID_QUEUE_FULL() { return (int)3224829955L; }

    static final int ERROR_VID_HANDLER_NOT_PRESENT() { return (int)3224829956L; }

    static final int ERROR_VID_INVALID_OBJECT_NAME() { return (int)3224829957L; }

    static final int ERROR_VID_PARTITION_NAME_TOO_LONG() { return (int)3224829958L; }

    static final int ERROR_VID_MESSAGE_QUEUE_NAME_TOO_LONG() { return (int)3224829959L; }

    static final int ERROR_VID_PARTITION_ALREADY_EXISTS() { return (int)3224829960L; }

    static final int ERROR_VID_PARTITION_DOES_NOT_EXIST() { return (int)3224829961L; }

    static final int ERROR_VID_PARTITION_NAME_NOT_FOUND() { return (int)3224829962L; }

    static final int ERROR_VID_MESSAGE_QUEUE_ALREADY_EXISTS() { return (int)3224829963L; }

    static final int ERROR_VID_EXCEEDED_MBP_ENTRY_MAP_LIMIT() { return (int)3224829964L; }

    static final int ERROR_VID_MB_STILL_REFERENCED() { return (int)3224829965L; }

    static final int ERROR_VID_CHILD_GPA_PAGE_SET_CORRUPTED() { return (int)3224829966L; }

    static final int ERROR_VID_INVALID_NUMA_SETTINGS() { return (int)3224829967L; }

    static final int ERROR_VID_INVALID_NUMA_NODE_INDEX() { return (int)3224829968L; }

    static final int ERROR_VID_NOTIFICATION_QUEUE_ALREADY_ASSOCIATED() { return (int)3224829969L; }

    static final int ERROR_VID_INVALID_MEMORY_BLOCK_HANDLE() { return (int)3224829970L; }

    static final int ERROR_VID_PAGE_RANGE_OVERFLOW() { return (int)3224829971L; }

    static final int ERROR_VID_INVALID_MESSAGE_QUEUE_HANDLE() { return (int)3224829972L; }

    static final int ERROR_VID_INVALID_GPA_RANGE_HANDLE() { return (int)3224829973L; }

    static final int ERROR_VID_NO_MEMORY_BLOCK_NOTIFICATION_QUEUE() { return (int)3224829974L; }

    static final int ERROR_VID_MEMORY_BLOCK_LOCK_COUNT_EXCEEDED() { return (int)3224829975L; }

    static final int ERROR_VID_INVALID_PPM_HANDLE() { return (int)3224829976L; }

    static final int ERROR_VID_MBPS_ARE_LOCKED() { return (int)3224829977L; }

    static final int ERROR_VID_MESSAGE_QUEUE_CLOSED() { return (int)3224829978L; }

    static final int ERROR_VID_VIRTUAL_PROCESSOR_LIMIT_EXCEEDED() { return (int)3224829979L; }

    static final int ERROR_VID_STOP_PENDING() { return (int)3224829980L; }

    static final int ERROR_VID_INVALID_PROCESSOR_STATE() { return (int)3224829981L; }

    static final int ERROR_VID_EXCEEDED_KM_CONTEXT_COUNT_LIMIT() { return (int)3224829982L; }

    static final int ERROR_VID_KM_INTERFACE_ALREADY_INITIALIZED() { return (int)3224829983L; }

    static final int ERROR_VID_MB_PROPERTY_ALREADY_SET_RESET() { return (int)3224829984L; }

    static final int ERROR_VID_MMIO_RANGE_DESTROYED() { return (int)3224829985L; }

    static final int ERROR_VID_INVALID_CHILD_GPA_PAGE_SET() { return (int)3224829986L; }

    static final int ERROR_VID_RESERVE_PAGE_SET_IS_BEING_USED() { return (int)3224829987L; }

    static final int ERROR_VID_RESERVE_PAGE_SET_TOO_SMALL() { return (int)3224829988L; }

    static final int ERROR_VID_MBP_ALREADY_LOCKED_USING_RESERVED_PAGE() { return (int)3224829989L; }

    static final int ERROR_VID_MBP_COUNT_EXCEEDED_LIMIT() { return (int)3224829990L; }

    static final int ERROR_VID_SAVED_STATE_CORRUPT() { return (int)3224829991L; }

    static final int ERROR_VID_SAVED_STATE_UNRECOGNIZED_ITEM() { return (int)3224829992L; }

    static final int ERROR_VID_SAVED_STATE_INCOMPATIBLE() { return (int)3224829993L; }

    static final int ERROR_VID_VTL_ACCESS_DENIED() { return (int)3224829994L; }

    static final int ERROR_VMCOMPUTE_TERMINATED_DURING_START() { return (int)3224830208L; }

    static final int ERROR_VMCOMPUTE_IMAGE_MISMATCH() { return (int)3224830209L; }

    static final int ERROR_VMCOMPUTE_HYPERV_NOT_INSTALLED() { return (int)3224830210L; }

    static final int ERROR_VMCOMPUTE_OPERATION_PENDING() { return (int)3224830211L; }

    static final int ERROR_VMCOMPUTE_TOO_MANY_NOTIFICATIONS() { return (int)3224830212L; }

    static final int ERROR_VMCOMPUTE_INVALID_STATE() { return (int)3224830213L; }

    static final int ERROR_VMCOMPUTE_UNEXPECTED_EXIT() { return (int)3224830214L; }

    static final int ERROR_VMCOMPUTE_TERMINATED() { return (int)3224830215L; }

    static final int ERROR_VMCOMPUTE_CONNECT_FAILED() { return (int)3224830216L; }

    static final int ERROR_VMCOMPUTE_TIMEOUT() { return (int)3224830217L; }

    static final int ERROR_VMCOMPUTE_CONNECTION_CLOSED() { return (int)3224830218L; }

    static final int ERROR_VMCOMPUTE_UNKNOWN_MESSAGE() { return (int)3224830219L; }

    static final int ERROR_VMCOMPUTE_UNSUPPORTED_PROTOCOL_VERSION() { return (int)3224830220L; }

    static final int ERROR_VMCOMPUTE_INVALID_JSON() { return (int)3224830221L; }

    static final int ERROR_VMCOMPUTE_SYSTEM_NOT_FOUND() { return (int)3224830222L; }

    static final int ERROR_VMCOMPUTE_SYSTEM_ALREADY_EXISTS() { return (int)3224830223L; }

    static final int ERROR_VMCOMPUTE_SYSTEM_ALREADY_STOPPED() { return (int)3224830224L; }

    static final int ERROR_VMCOMPUTE_PROTOCOL_ERROR() { return (int)3224830225L; }

    static final int ERROR_VMCOMPUTE_INVALID_LAYER() { return (int)3224830226L; }

    static final int ERROR_VMCOMPUTE_WINDOWS_INSIDER_REQUIRED() { return (int)3224830227L; }

    static final int HCS_E_TERMINATED_DURING_START() { return (int)-2143878912L; }

    static final int HCS_E_IMAGE_MISMATCH() { return (int)-2143878911L; }

    static final int HCS_E_HYPERV_NOT_INSTALLED() { return (int)-2143878910L; }

    static final int HCS_E_INVALID_STATE() { return (int)-2143878907L; }

    static final int HCS_E_UNEXPECTED_EXIT() { return (int)-2143878906L; }

    static final int HCS_E_TERMINATED() { return (int)-2143878905L; }

    static final int HCS_E_CONNECT_FAILED() { return (int)-2143878904L; }

    static final int HCS_E_CONNECTION_TIMEOUT() { return (int)-2143878903L; }

    static final int HCS_E_CONNECTION_CLOSED() { return (int)-2143878902L; }

    static final int HCS_E_UNKNOWN_MESSAGE() { return (int)-2143878901L; }

    static final int HCS_E_UNSUPPORTED_PROTOCOL_VERSION() { return (int)-2143878900L; }

    static final int HCS_E_INVALID_JSON() { return (int)-2143878899L; }

    static final int HCS_E_SYSTEM_NOT_FOUND() { return (int)-2143878898L; }

    static final int HCS_E_SYSTEM_ALREADY_EXISTS() { return (int)-2143878897L; }

    static final int HCS_E_SYSTEM_ALREADY_STOPPED() { return (int)-2143878896L; }

    static final int HCS_E_PROTOCOL_ERROR() { return (int)-2143878895L; }

    static final int HCS_E_INVALID_LAYER() { return (int)-2143878894L; }

    static final int HCS_E_WINDOWS_INSIDER_REQUIRED() { return (int)-2143878893L; }

    static final int HCS_E_SERVICE_NOT_AVAILABLE() { return (int)-2143878892L; }

    static final int HCS_E_OPERATION_NOT_STARTED() { return (int)-2143878891L; }

    static final int HCS_E_OPERATION_ALREADY_STARTED() { return (int)-2143878890L; }

    static final int HCS_E_OPERATION_PENDING() { return (int)-2143878889L; }

    static final int HCS_E_OPERATION_TIMEOUT() { return (int)-2143878888L; }

    static final int HCS_E_OPERATION_SYSTEM_CALLBACK_ALREADY_SET() { return (int)-2143878887L; }

    static final int HCS_E_OPERATION_RESULT_ALLOCATION_FAILED() { return (int)-2143878886L; }

    static final int HCS_E_ACCESS_DENIED() { return (int)-2143878885L; }

    static final int HCS_E_GUEST_CRITICAL_ERROR() { return (int)-2143878884L; }

    static final int HCS_E_PROCESS_INFO_NOT_AVAILABLE() { return (int)-2143878883L; }

    static final int HCS_E_SERVICE_DISCONNECT() { return (int)-2143878882L; }

    static final int HCS_E_PROCESS_ALREADY_STOPPED() { return (int)-2143878881L; }

    static final int ERROR_VNET_VIRTUAL_SWITCH_NAME_NOT_FOUND() { return (int)3224830464L; }

    static final int ERROR_VID_REMOTE_NODE_PARENT_GPA_PAGES_USED() { return (int)2151088129L; }

    static final int WHV_E_UNKNOWN_CAPABILITY() { return (int)-2143878400L; }

    static final int WHV_E_INSUFFICIENT_BUFFER() { return (int)-2143878399L; }

    static final int WHV_E_UNKNOWN_PROPERTY() { return (int)-2143878398L; }

    static final int WHV_E_UNSUPPORTED_HYPERVISOR_CONFIG() { return (int)-2143878397L; }

    static final int WHV_E_INVALID_PARTITION_CONFIG() { return (int)-2143878396L; }

    static final int WHV_E_GPA_RANGE_NOT_FOUND() { return (int)-2143878395L; }

    static final int WHV_E_VP_ALREADY_EXISTS() { return (int)-2143878394L; }

    static final int WHV_E_VP_DOES_NOT_EXIST() { return (int)-2143878393L; }

    static final int WHV_E_INVALID_VP_STATE() { return (int)-2143878392L; }

    static final int WHV_E_INVALID_VP_REGISTER_NAME() { return (int)-2143878391L; }

    static final int WHV_E_UNSUPPORTED_PROCESSOR_CONFIG() { return (int)-2143878384L; }

    static final int ERROR_VSMB_SAVED_STATE_FILE_NOT_FOUND() { return (int)3224830976L; }

    static final int ERROR_VSMB_SAVED_STATE_CORRUPT() { return (int)3224830977L; }

    static final int VM_SAVED_STATE_DUMP_E_PARTITION_STATE_NOT_FOUND() { return (int)-1070136064L; }

    static final int VM_SAVED_STATE_DUMP_E_GUEST_MEMORY_NOT_FOUND() { return (int)-1070136063L; }

    static final int VM_SAVED_STATE_DUMP_E_NO_VP_FOUND_IN_PARTITION_STATE() { return (int)-1070136062L; }

    static final int VM_SAVED_STATE_DUMP_E_NESTED_VIRTUALIZATION_NOT_SUPPORTED() { return (int)-1070136061L; }

    static final int VM_SAVED_STATE_DUMP_E_WINDOWS_KERNEL_IMAGE_NOT_FOUND() { return (int)-1070136060L; }

    static final int VM_SAVED_STATE_DUMP_E_PXE_NOT_PRESENT() { return (int)-1070136059L; }

    static final int VM_SAVED_STATE_DUMP_E_PDPTE_NOT_PRESENT() { return (int)-1070136058L; }

    static final int VM_SAVED_STATE_DUMP_E_PDE_NOT_PRESENT() { return (int)-1070136057L; }

    static final int VM_SAVED_STATE_DUMP_E_PTE_NOT_PRESENT() { return (int)-1070136056L; }

    static final int ERROR_VOLMGR_INCOMPLETE_REGENERATION() { return (int)2151153665L; }

    static final int ERROR_VOLMGR_INCOMPLETE_DISK_MIGRATION() { return (int)2151153666L; }

    static final int ERROR_VOLMGR_DATABASE_FULL() { return (int)3224895489L; }

    static final int ERROR_VOLMGR_DISK_CONFIGURATION_CORRUPTED() { return (int)3224895490L; }

    static final int ERROR_VOLMGR_DISK_CONFIGURATION_NOT_IN_SYNC() { return (int)3224895491L; }

    static final int ERROR_VOLMGR_PACK_CONFIG_UPDATE_FAILED() { return (int)3224895492L; }

    static final int ERROR_VOLMGR_DISK_CONTAINS_NON_SIMPLE_VOLUME() { return (int)3224895493L; }

    static final int ERROR_VOLMGR_DISK_DUPLICATE() { return (int)3224895494L; }

    static final int ERROR_VOLMGR_DISK_DYNAMIC() { return (int)3224895495L; }

    static final int ERROR_VOLMGR_DISK_ID_INVALID() { return (int)3224895496L; }

    static final int ERROR_VOLMGR_DISK_INVALID() { return (int)3224895497L; }

    static final int ERROR_VOLMGR_DISK_LAST_VOTER() { return (int)3224895498L; }

    static final int ERROR_VOLMGR_DISK_LAYOUT_INVALID() { return (int)3224895499L; }

    static final int ERROR_VOLMGR_DISK_LAYOUT_NON_BASIC_BETWEEN_BASIC_PARTITIONS() { return (int)3224895500L; }

    static final int ERROR_VOLMGR_DISK_LAYOUT_NOT_CYLINDER_ALIGNED() { return (int)3224895501L; }

    static final int ERROR_VOLMGR_DISK_LAYOUT_PARTITIONS_TOO_SMALL() { return (int)3224895502L; }

    static final int ERROR_VOLMGR_DISK_LAYOUT_PRIMARY_BETWEEN_LOGICAL_PARTITIONS() { return (int)3224895503L; }

    static final int ERROR_VOLMGR_DISK_LAYOUT_TOO_MANY_PARTITIONS() { return (int)3224895504L; }

    static final int ERROR_VOLMGR_DISK_MISSING() { return (int)3224895505L; }

    static final int ERROR_VOLMGR_DISK_NOT_EMPTY() { return (int)3224895506L; }

    static final int ERROR_VOLMGR_DISK_NOT_ENOUGH_SPACE() { return (int)3224895507L; }

    static final int ERROR_VOLMGR_DISK_REVECTORING_FAILED() { return (int)3224895508L; }

    static final int ERROR_VOLMGR_DISK_SECTOR_SIZE_INVALID() { return (int)3224895509L; }

    static final int ERROR_VOLMGR_DISK_SET_NOT_CONTAINED() { return (int)3224895510L; }

    static final int ERROR_VOLMGR_DISK_USED_BY_MULTIPLE_MEMBERS() { return (int)3224895511L; }

    static final int ERROR_VOLMGR_DISK_USED_BY_MULTIPLE_PLEXES() { return (int)3224895512L; }

    static final int ERROR_VOLMGR_DYNAMIC_DISK_NOT_SUPPORTED() { return (int)3224895513L; }

    static final int ERROR_VOLMGR_EXTENT_ALREADY_USED() { return (int)3224895514L; }

    static final int ERROR_VOLMGR_EXTENT_NOT_CONTIGUOUS() { return (int)3224895515L; }

    static final int ERROR_VOLMGR_EXTENT_NOT_IN_PUBLIC_REGION() { return (int)3224895516L; }

    static final int ERROR_VOLMGR_EXTENT_NOT_SECTOR_ALIGNED() { return (int)3224895517L; }

    static final int ERROR_VOLMGR_EXTENT_OVERLAPS_EBR_PARTITION() { return (int)3224895518L; }

    static final int ERROR_VOLMGR_EXTENT_VOLUME_LENGTHS_DO_NOT_MATCH() { return (int)3224895519L; }

    static final int ERROR_VOLMGR_FAULT_TOLERANT_NOT_SUPPORTED() { return (int)3224895520L; }

    static final int ERROR_VOLMGR_INTERLEAVE_LENGTH_INVALID() { return (int)3224895521L; }

    static final int ERROR_VOLMGR_MAXIMUM_REGISTERED_USERS() { return (int)3224895522L; }

    static final int ERROR_VOLMGR_MEMBER_IN_SYNC() { return (int)3224895523L; }

    static final int ERROR_VOLMGR_MEMBER_INDEX_DUPLICATE() { return (int)3224895524L; }

    static final int ERROR_VOLMGR_MEMBER_INDEX_INVALID() { return (int)3224895525L; }

    static final int ERROR_VOLMGR_MEMBER_MISSING() { return (int)3224895526L; }

    static final int ERROR_VOLMGR_MEMBER_NOT_DETACHED() { return (int)3224895527L; }

    static final int ERROR_VOLMGR_MEMBER_REGENERATING() { return (int)3224895528L; }

    static final int ERROR_VOLMGR_ALL_DISKS_FAILED() { return (int)3224895529L; }

    static final int ERROR_VOLMGR_NO_REGISTERED_USERS() { return (int)3224895530L; }

    static final int ERROR_VOLMGR_NO_SUCH_USER() { return (int)3224895531L; }

    static final int ERROR_VOLMGR_NOTIFICATION_RESET() { return (int)3224895532L; }

    static final int ERROR_VOLMGR_NUMBER_OF_MEMBERS_INVALID() { return (int)3224895533L; }

    static final int ERROR_VOLMGR_NUMBER_OF_PLEXES_INVALID() { return (int)3224895534L; }

    static final int ERROR_VOLMGR_PACK_DUPLICATE() { return (int)3224895535L; }

    static final int ERROR_VOLMGR_PACK_ID_INVALID() { return (int)3224895536L; }

    static final int ERROR_VOLMGR_PACK_INVALID() { return (int)3224895537L; }

    static final int ERROR_VOLMGR_PACK_NAME_INVALID() { return (int)3224895538L; }

    static final int ERROR_VOLMGR_PACK_OFFLINE() { return (int)3224895539L; }

    static final int ERROR_VOLMGR_PACK_HAS_QUORUM() { return (int)3224895540L; }

    static final int ERROR_VOLMGR_PACK_WITHOUT_QUORUM() { return (int)3224895541L; }

    static final int ERROR_VOLMGR_PARTITION_STYLE_INVALID() { return (int)3224895542L; }

    static final int ERROR_VOLMGR_PARTITION_UPDATE_FAILED() { return (int)3224895543L; }

    static final int ERROR_VOLMGR_PLEX_IN_SYNC() { return (int)3224895544L; }

    static final int ERROR_VOLMGR_PLEX_INDEX_DUPLICATE() { return (int)3224895545L; }

    static final int ERROR_VOLMGR_PLEX_INDEX_INVALID() { return (int)3224895546L; }

    static final int ERROR_VOLMGR_PLEX_LAST_ACTIVE() { return (int)3224895547L; }

    static final int ERROR_VOLMGR_PLEX_MISSING() { return (int)3224895548L; }

    static final int ERROR_VOLMGR_PLEX_REGENERATING() { return (int)3224895549L; }

    static final int ERROR_VOLMGR_PLEX_TYPE_INVALID() { return (int)3224895550L; }

    static final int ERROR_VOLMGR_PLEX_NOT_RAID5() { return (int)3224895551L; }

    static final int ERROR_VOLMGR_PLEX_NOT_SIMPLE() { return (int)3224895552L; }

    static final int ERROR_VOLMGR_STRUCTURE_SIZE_INVALID() { return (int)3224895553L; }

    static final int ERROR_VOLMGR_TOO_MANY_NOTIFICATION_REQUESTS() { return (int)3224895554L; }

    static final int ERROR_VOLMGR_TRANSACTION_IN_PROGRESS() { return (int)3224895555L; }

    static final int ERROR_VOLMGR_UNEXPECTED_DISK_LAYOUT_CHANGE() { return (int)3224895556L; }

    static final int ERROR_VOLMGR_VOLUME_CONTAINS_MISSING_DISK() { return (int)3224895557L; }

    static final int ERROR_VOLMGR_VOLUME_ID_INVALID() { return (int)3224895558L; }

    static final int ERROR_VOLMGR_VOLUME_LENGTH_INVALID() { return (int)3224895559L; }

    static final int ERROR_VOLMGR_VOLUME_LENGTH_NOT_SECTOR_SIZE_MULTIPLE() { return (int)3224895560L; }

    static final int ERROR_VOLMGR_VOLUME_NOT_MIRRORED() { return (int)3224895561L; }

    static final int ERROR_VOLMGR_VOLUME_NOT_RETAINED() { return (int)3224895562L; }

    static final int ERROR_VOLMGR_VOLUME_OFFLINE() { return (int)3224895563L; }

    static final int ERROR_VOLMGR_VOLUME_RETAINED() { return (int)3224895564L; }

    static final int ERROR_VOLMGR_NUMBER_OF_EXTENTS_INVALID() { return (int)3224895565L; }

    static final int ERROR_VOLMGR_DIFFERENT_SECTOR_SIZE() { return (int)3224895566L; }

    static final int ERROR_VOLMGR_BAD_BOOT_DISK() { return (int)3224895567L; }

    static final int ERROR_VOLMGR_PACK_CONFIG_OFFLINE() { return (int)3224895568L; }

    static final int ERROR_VOLMGR_PACK_CONFIG_ONLINE() { return (int)3224895569L; }

    static final int ERROR_VOLMGR_NOT_PRIMARY_PACK() { return (int)3224895570L; }

    static final int ERROR_VOLMGR_PACK_LOG_UPDATE_FAILED() { return (int)3224895571L; }

    static final int ERROR_VOLMGR_NUMBER_OF_DISKS_IN_PLEX_INVALID() { return (int)3224895572L; }

    static final int ERROR_VOLMGR_NUMBER_OF_DISKS_IN_MEMBER_INVALID() { return (int)3224895573L; }

    static final int ERROR_VOLMGR_VOLUME_MIRRORED() { return (int)3224895574L; }

    static final int ERROR_VOLMGR_PLEX_NOT_SIMPLE_SPANNED() { return (int)3224895575L; }

    static final int ERROR_VOLMGR_NO_VALID_LOG_COPIES() { return (int)3224895576L; }

    static final int ERROR_VOLMGR_PRIMARY_PACK_PRESENT() { return (int)3224895577L; }

    static final int ERROR_VOLMGR_NUMBER_OF_DISKS_INVALID() { return (int)3224895578L; }

    static final int ERROR_VOLMGR_MIRROR_NOT_SUPPORTED() { return (int)3224895579L; }

    static final int ERROR_VOLMGR_RAID5_NOT_SUPPORTED() { return (int)3224895580L; }

    static final int ERROR_BCD_NOT_ALL_ENTRIES_IMPORTED() { return (int)2151219201L; }

    static final int ERROR_BCD_TOO_MANY_ELEMENTS() { return (int)3224961026L; }

    static final int ERROR_BCD_NOT_ALL_ENTRIES_SYNCHRONIZED() { return (int)2151219203L; }

    static final int ERROR_VHD_DRIVE_FOOTER_MISSING() { return (int)3225026561L; }

    static final int ERROR_VHD_DRIVE_FOOTER_CHECKSUM_MISMATCH() { return (int)3225026562L; }

    static final int ERROR_VHD_DRIVE_FOOTER_CORRUPT() { return (int)3225026563L; }

    static final int ERROR_VHD_FORMAT_UNKNOWN() { return (int)3225026564L; }

    static final int ERROR_VHD_FORMAT_UNSUPPORTED_VERSION() { return (int)3225026565L; }

    static final int ERROR_VHD_SPARSE_HEADER_CHECKSUM_MISMATCH() { return (int)3225026566L; }

    static final int ERROR_VHD_SPARSE_HEADER_UNSUPPORTED_VERSION() { return (int)3225026567L; }

    static final int ERROR_VHD_SPARSE_HEADER_CORRUPT() { return (int)3225026568L; }

    static final int ERROR_VHD_BLOCK_ALLOCATION_FAILURE() { return (int)3225026569L; }

    static final int ERROR_VHD_BLOCK_ALLOCATION_TABLE_CORRUPT() { return (int)3225026570L; }

    static final int ERROR_VHD_INVALID_BLOCK_SIZE() { return (int)3225026571L; }

    static final int ERROR_VHD_BITMAP_MISMATCH() { return (int)3225026572L; }

    static final int ERROR_VHD_PARENT_VHD_NOT_FOUND() { return (int)3225026573L; }

    static final int ERROR_VHD_CHILD_PARENT_ID_MISMATCH() { return (int)3225026574L; }

    static final int ERROR_VHD_CHILD_PARENT_TIMESTAMP_MISMATCH() { return (int)3225026575L; }

    static final int ERROR_VHD_METADATA_READ_FAILURE() { return (int)3225026576L; }

    static final int ERROR_VHD_METADATA_WRITE_FAILURE() { return (int)3225026577L; }

    static final int ERROR_VHD_INVALID_SIZE() { return (int)3225026578L; }

    static final int ERROR_VHD_INVALID_FILE_SIZE() { return (int)3225026579L; }

    static final int ERROR_VIRTDISK_PROVIDER_NOT_FOUND() { return (int)3225026580L; }

    static final int ERROR_VIRTDISK_NOT_VIRTUAL_DISK() { return (int)3225026581L; }

    static final int ERROR_VHD_PARENT_VHD_ACCESS_DENIED() { return (int)3225026582L; }

    static final int ERROR_VHD_CHILD_PARENT_SIZE_MISMATCH() { return (int)3225026583L; }

    static final int ERROR_VHD_DIFFERENCING_CHAIN_CYCLE_DETECTED() { return (int)3225026584L; }

    static final int ERROR_VHD_DIFFERENCING_CHAIN_ERROR_IN_PARENT() { return (int)3225026585L; }

    static final int ERROR_VIRTUAL_DISK_LIMITATION() { return (int)3225026586L; }

    static final int ERROR_VHD_INVALID_TYPE() { return (int)3225026587L; }

    static final int ERROR_VHD_INVALID_STATE() { return (int)3225026588L; }

    static final int ERROR_VIRTDISK_UNSUPPORTED_DISK_SECTOR_SIZE() { return (int)3225026589L; }

    static final int ERROR_VIRTDISK_DISK_ALREADY_OWNED() { return (int)3225026590L; }

    static final int ERROR_VIRTDISK_DISK_ONLINE_AND_WRITABLE() { return (int)3225026591L; }

    static final int ERROR_CTLOG_TRACKING_NOT_INITIALIZED() { return (int)3225026592L; }

    static final int ERROR_CTLOG_LOGFILE_SIZE_EXCEEDED_MAXSIZE() { return (int)3225026593L; }

    static final int ERROR_CTLOG_VHD_CHANGED_OFFLINE() { return (int)3225026594L; }

    static final int ERROR_CTLOG_INVALID_TRACKING_STATE() { return (int)3225026595L; }

    static final int ERROR_CTLOG_INCONSISTENT_TRACKING_FILE() { return (int)3225026596L; }

    static final int ERROR_VHD_RESIZE_WOULD_TRUNCATE_DATA() { return (int)3225026597L; }

    static final int ERROR_VHD_COULD_NOT_COMPUTE_MINIMUM_VIRTUAL_SIZE() { return (int)3225026598L; }

    static final int ERROR_VHD_ALREADY_AT_OR_BELOW_MINIMUM_VIRTUAL_SIZE() { return (int)3225026599L; }

    static final int ERROR_VHD_METADATA_FULL() { return (int)3225026600L; }

    static final int ERROR_VHD_INVALID_CHANGE_TRACKING_ID() { return (int)3225026601L; }

    static final int ERROR_VHD_CHANGE_TRACKING_DISABLED() { return (int)3225026602L; }

    static final int ERROR_VHD_MISSING_CHANGE_TRACKING_INFORMATION() { return (int)3225026608L; }

    static final int ERROR_QUERY_STORAGE_ERROR() { return (int)2151284737L; }

    static final int HCN_E_NETWORK_NOT_FOUND() { return (int)-2143617023L; }

    static final int HCN_E_ENDPOINT_NOT_FOUND() { return (int)-2143617022L; }

    static final int HCN_E_LAYER_NOT_FOUND() { return (int)-2143617021L; }

    static final int HCN_E_SWITCH_NOT_FOUND() { return (int)-2143617020L; }

    static final int HCN_E_SUBNET_NOT_FOUND() { return (int)-2143617019L; }

    static final int HCN_E_ADAPTER_NOT_FOUND() { return (int)-2143617018L; }

    static final int HCN_E_PORT_NOT_FOUND() { return (int)-2143617017L; }

    static final int HCN_E_POLICY_NOT_FOUND() { return (int)-2143617016L; }

    static final int HCN_E_VFP_PORTSETTING_NOT_FOUND() { return (int)-2143617015L; }

    static final int HCN_E_INVALID_NETWORK() { return (int)-2143617014L; }

    static final int HCN_E_INVALID_NETWORK_TYPE() { return (int)-2143617013L; }

    static final int HCN_E_INVALID_ENDPOINT() { return (int)-2143617012L; }

    static final int HCN_E_INVALID_POLICY() { return (int)-2143617011L; }

    static final int HCN_E_INVALID_POLICY_TYPE() { return (int)-2143617010L; }

    static final int HCN_E_INVALID_REMOTE_ENDPOINT_OPERATION() { return (int)-2143617009L; }

    static final int HCN_E_NETWORK_ALREADY_EXISTS() { return (int)-2143617008L; }

    static final int HCN_E_LAYER_ALREADY_EXISTS() { return (int)-2143617007L; }

    static final int HCN_E_POLICY_ALREADY_EXISTS() { return (int)-2143617006L; }

    static final int HCN_E_PORT_ALREADY_EXISTS() { return (int)-2143617005L; }

    static final int HCN_E_ENDPOINT_ALREADY_ATTACHED() { return (int)-2143617004L; }

    static final int HCN_E_REQUEST_UNSUPPORTED() { return (int)-2143617003L; }

    static final int HCN_E_MAPPING_NOT_SUPPORTED() { return (int)-2143617002L; }

    static final int HCN_E_DEGRADED_OPERATION() { return (int)-2143617001L; }

    static final int HCN_E_SHARED_SWITCH_MODIFICATION() { return (int)-2143617000L; }

    static final int HCN_E_GUID_CONVERSION_FAILURE() { return (int)-2143616999L; }

    static final int HCN_E_REGKEY_FAILURE() { return (int)-2143616998L; }

    static final int HCN_E_INVALID_JSON() { return (int)-2143616997L; }

    static final int HCN_E_INVALID_JSON_REFERENCE() { return (int)-2143616996L; }

    static final int HCN_E_ENDPOINT_SHARING_DISABLED() { return (int)-2143616995L; }

    static final int HCN_E_INVALID_IP() { return (int)-2143616994L; }

    static final int HCN_E_SWITCH_EXTENSION_NOT_FOUND() { return (int)-2143616993L; }

    static final int HCN_E_MANAGER_STOPPED() { return (int)-2143616992L; }

    static final int GCN_E_MODULE_NOT_FOUND() { return (int)-2143616991L; }

    static final int GCN_E_NO_REQUEST_HANDLERS() { return (int)-2143616990L; }

    static final int GCN_E_REQUEST_UNSUPPORTED() { return (int)-2143616989L; }

    static final int GCN_E_RUNTIMEKEYS_FAILED() { return (int)-2143616988L; }

    static final int GCN_E_NETADAPTER_TIMEOUT() { return (int)-2143616987L; }

    static final int GCN_E_NETADAPTER_NOT_FOUND() { return (int)-2143616986L; }

    static final int GCN_E_NETCOMPARTMENT_NOT_FOUND() { return (int)-2143616985L; }

    static final int GCN_E_NETINTERFACE_NOT_FOUND() { return (int)-2143616984L; }

    static final int GCN_E_DEFAULTNAMESPACE_EXISTS() { return (int)-2143616983L; }

    static final int HCN_E_ICS_DISABLED() { return (int)-2143616982L; }

    static final int HCN_E_ENDPOINT_NAMESPACE_ALREADY_EXISTS() { return (int)-2143616981L; }

    static final int HCN_E_ENTITY_HAS_REFERENCES() { return (int)-2143616980L; }

    static final int HCN_E_INVALID_INTERNAL_PORT() { return (int)-2143616979L; }

    static final int HCN_E_NAMESPACE_ATTACH_FAILED() { return (int)-2143616978L; }

    static final int HCN_E_ADDR_INVALID_OR_RESERVED() { return (int)-2143616977L; }

    static final int HCN_E_INVALID_PREFIX() { return (int)-2143616976L; }

    static final int HCN_E_OBJECT_USED_AFTER_UNLOAD() { return (int)-2143616975L; }

    static final int HCN_E_INVALID_SUBNET() { return (int)-2143616974L; }

    static final int HCN_E_INVALID_IP_SUBNET() { return (int)-2143616973L; }

    static final int HCN_E_ENDPOINT_NOT_ATTACHED() { return (int)-2143616972L; }

    static final int HCN_E_ENDPOINT_NOT_LOCAL() { return (int)-2143616971L; }

    static final int HCN_INTERFACEPARAMETERS_ALREADY_APPLIED() { return (int)-2143616970L; }

    static final int SDIAG_E_CANCELLED() { return (int)2151416064L; }

    static final int SDIAG_E_SCRIPT() { return (int)2151416065L; }

    static final int SDIAG_E_POWERSHELL() { return (int)2151416066L; }

    static final int SDIAG_E_MANAGEDHOST() { return (int)2151416067L; }

    static final int SDIAG_E_NOVERIFIER() { return (int)2151416068L; }

    static final int SDIAG_S_CANNOTRUN() { return (int)3932421L; }

    static final int SDIAG_E_DISABLED() { return (int)2151416070L; }

    static final int SDIAG_E_TRUST() { return (int)2151416071L; }

    static final int SDIAG_E_CANNOTRUN() { return (int)2151416072L; }

    static final int SDIAG_E_VERSION() { return (int)2151416073L; }

    static final int SDIAG_E_RESOURCE() { return (int)2151416074L; }

    static final int SDIAG_E_ROOTCAUSE() { return (int)2151416075L; }

    static final int WPN_E_CHANNEL_CLOSED() { return (int)-2143420160L; }

    static final int WPN_E_CHANNEL_REQUEST_NOT_COMPLETE() { return (int)-2143420159L; }

    static final int WPN_E_INVALID_APP() { return (int)-2143420158L; }

    static final int WPN_E_OUTSTANDING_CHANNEL_REQUEST() { return (int)-2143420157L; }

    static final int WPN_E_DUPLICATE_CHANNEL() { return (int)-2143420156L; }

    static final int WPN_E_PLATFORM_UNAVAILABLE() { return (int)-2143420155L; }

    static final int WPN_E_NOTIFICATION_POSTED() { return (int)-2143420154L; }

    static final int WPN_E_NOTIFICATION_HIDDEN() { return (int)-2143420153L; }

    static final int WPN_E_NOTIFICATION_NOT_POSTED() { return (int)-2143420152L; }

    static final int WPN_E_CLOUD_DISABLED() { return (int)-2143420151L; }

    static final int WPN_E_CLOUD_INCAPABLE() { return (int)-2143420144L; }

    static final int WPN_E_CLOUD_AUTH_UNAVAILABLE() { return (int)-2143420134L; }

    static final int WPN_E_CLOUD_SERVICE_UNAVAILABLE() { return (int)-2143420133L; }

    static final int WPN_E_FAILED_LOCK_SCREEN_UPDATE_INTIALIZATION() { return (int)-2143420132L; }

    static final int WPN_E_NOTIFICATION_DISABLED() { return (int)-2143420143L; }

    static final int WPN_E_NOTIFICATION_INCAPABLE() { return (int)-2143420142L; }

    static final int WPN_E_INTERNET_INCAPABLE() { return (int)-2143420141L; }

    static final int WPN_E_NOTIFICATION_TYPE_DISABLED() { return (int)-2143420140L; }

    static final int WPN_E_NOTIFICATION_SIZE() { return (int)-2143420139L; }

    static final int WPN_E_TAG_SIZE() { return (int)-2143420138L; }

    static final int WPN_E_ACCESS_DENIED() { return (int)-2143420137L; }

    static final int WPN_E_DUPLICATE_REGISTRATION() { return (int)-2143420136L; }

    static final int WPN_E_PUSH_NOTIFICATION_INCAPABLE() { return (int)-2143420135L; }

    static final int WPN_E_DEV_ID_SIZE() { return (int)-2143420128L; }

    static final int WPN_E_TAG_ALPHANUMERIC() { return (int)-2143420118L; }

    static final int WPN_E_INVALID_HTTP_STATUS_CODE() { return (int)-2143420117L; }

    static final int WPN_E_OUT_OF_SESSION() { return (int)-2143419904L; }

    static final int WPN_E_POWER_SAVE() { return (int)-2143419903L; }

    static final int WPN_E_IMAGE_NOT_FOUND_IN_CACHE() { return (int)-2143419902L; }

    static final int WPN_E_ALL_URL_NOT_COMPLETED() { return (int)-2143419901L; }

    static final int WPN_E_INVALID_CLOUD_IMAGE() { return (int)-2143419900L; }

    static final int WPN_E_NOTIFICATION_ID_MATCHED() { return (int)-2143419899L; }

    static final int WPN_E_CALLBACK_ALREADY_REGISTERED() { return (int)-2143419898L; }

    static final int WPN_E_TOAST_NOTIFICATION_DROPPED() { return (int)-2143419897L; }

    static final int WPN_E_STORAGE_LOCKED() { return (int)-2143419896L; }

    static final int WPN_E_GROUP_SIZE() { return (int)-2143419895L; }

    static final int WPN_E_GROUP_ALPHANUMERIC() { return (int)-2143419894L; }

    static final int WPN_E_CLOUD_DISABLED_FOR_APP() { return (int)-2143419893L; }

    static final int E_MBN_CONTEXT_NOT_ACTIVATED() { return (int)-2141945343L; }

    static final int E_MBN_BAD_SIM() { return (int)-2141945342L; }

    static final int E_MBN_DATA_CLASS_NOT_AVAILABLE() { return (int)-2141945341L; }

    static final int E_MBN_INVALID_ACCESS_STRING() { return (int)-2141945340L; }

    static final int E_MBN_MAX_ACTIVATED_CONTEXTS() { return (int)-2141945339L; }

    static final int E_MBN_PACKET_SVC_DETACHED() { return (int)-2141945338L; }

    static final int E_MBN_PROVIDER_NOT_VISIBLE() { return (int)-2141945337L; }

    static final int E_MBN_RADIO_POWER_OFF() { return (int)-2141945336L; }

    static final int E_MBN_SERVICE_NOT_ACTIVATED() { return (int)-2141945335L; }

    static final int E_MBN_SIM_NOT_INSERTED() { return (int)-2141945334L; }

    static final int E_MBN_VOICE_CALL_IN_PROGRESS() { return (int)-2141945333L; }

    static final int E_MBN_INVALID_CACHE() { return (int)-2141945332L; }

    static final int E_MBN_NOT_REGISTERED() { return (int)-2141945331L; }

    static final int E_MBN_PROVIDERS_NOT_FOUND() { return (int)-2141945330L; }

    static final int E_MBN_PIN_NOT_SUPPORTED() { return (int)-2141945329L; }

    static final int E_MBN_PIN_REQUIRED() { return (int)-2141945328L; }

    static final int E_MBN_PIN_DISABLED() { return (int)-2141945327L; }

    static final int E_MBN_FAILURE() { return (int)-2141945326L; }

    static final int E_MBN_INVALID_PROFILE() { return (int)-2141945320L; }

    static final int E_MBN_DEFAULT_PROFILE_EXIST() { return (int)-2141945319L; }

    static final int E_MBN_SMS_ENCODING_NOT_SUPPORTED() { return (int)-2141945312L; }

    static final int E_MBN_SMS_FILTER_NOT_SUPPORTED() { return (int)-2141945311L; }

    static final int E_MBN_SMS_INVALID_MEMORY_INDEX() { return (int)-2141945310L; }

    static final int E_MBN_SMS_LANG_NOT_SUPPORTED() { return (int)-2141945309L; }

    static final int E_MBN_SMS_MEMORY_FAILURE() { return (int)-2141945308L; }

    static final int E_MBN_SMS_NETWORK_TIMEOUT() { return (int)-2141945307L; }

    static final int E_MBN_SMS_UNKNOWN_SMSC_ADDRESS() { return (int)-2141945306L; }

    static final int E_MBN_SMS_FORMAT_NOT_SUPPORTED() { return (int)-2141945305L; }

    static final int E_MBN_SMS_OPERATION_NOT_ALLOWED() { return (int)-2141945304L; }

    static final int E_MBN_SMS_MEMORY_FULL() { return (int)-2141945303L; }

    static final int PEER_E_IPV6_NOT_INSTALLED() { return (int)-2140995583L; }

    static final int PEER_E_NOT_INITIALIZED() { return (int)-2140995582L; }

    static final int PEER_E_CANNOT_START_SERVICE() { return (int)-2140995581L; }

    static final int PEER_E_NOT_LICENSED() { return (int)-2140995580L; }

    static final int PEER_E_INVALID_GRAPH() { return (int)-2140995568L; }

    static final int PEER_E_DBNAME_CHANGED() { return (int)-2140995567L; }

    static final int PEER_E_DUPLICATE_GRAPH() { return (int)-2140995566L; }

    static final int PEER_E_GRAPH_NOT_READY() { return (int)-2140995565L; }

    static final int PEER_E_GRAPH_SHUTTING_DOWN() { return (int)-2140995564L; }

    static final int PEER_E_GRAPH_IN_USE() { return (int)-2140995563L; }

    static final int PEER_E_INVALID_DATABASE() { return (int)-2140995562L; }

    static final int PEER_E_TOO_MANY_ATTRIBUTES() { return (int)-2140995561L; }

    static final int PEER_E_CONNECTION_NOT_FOUND() { return (int)-2140995325L; }

    static final int PEER_E_CONNECT_SELF() { return (int)-2140995322L; }

    static final int PEER_E_ALREADY_LISTENING() { return (int)-2140995321L; }

    static final int PEER_E_NODE_NOT_FOUND() { return (int)-2140995320L; }

    static final int PEER_E_CONNECTION_FAILED() { return (int)-2140995319L; }

    static final int PEER_E_CONNECTION_NOT_AUTHENTICATED() { return (int)-2140995318L; }

    static final int PEER_E_CONNECTION_REFUSED() { return (int)-2140995317L; }

    static final int PEER_E_CLASSIFIER_TOO_LONG() { return (int)-2140995071L; }

    static final int PEER_E_TOO_MANY_IDENTITIES() { return (int)-2140995070L; }

    static final int PEER_E_NO_KEY_ACCESS() { return (int)-2140995069L; }

    static final int PEER_E_GROUPS_EXIST() { return (int)-2140995068L; }

    static final int PEER_E_RECORD_NOT_FOUND() { return (int)-2140994815L; }

    static final int PEER_E_DATABASE_ACCESSDENIED() { return (int)-2140994814L; }

    static final int PEER_E_DBINITIALIZATION_FAILED() { return (int)-2140994813L; }

    static final int PEER_E_MAX_RECORD_SIZE_EXCEEDED() { return (int)-2140994812L; }

    static final int PEER_E_DATABASE_ALREADY_PRESENT() { return (int)-2140994811L; }

    static final int PEER_E_DATABASE_NOT_PRESENT() { return (int)-2140994810L; }

    static final int PEER_E_IDENTITY_NOT_FOUND() { return (int)-2140994559L; }

    static final int PEER_E_EVENT_HANDLE_NOT_FOUND() { return (int)-2140994303L; }

    static final int PEER_E_INVALID_SEARCH() { return (int)-2140994047L; }

    static final int PEER_E_INVALID_ATTRIBUTES() { return (int)-2140994046L; }

    static final int PEER_E_INVITATION_NOT_TRUSTED() { return (int)-2140993791L; }

    static final int PEER_E_CHAIN_TOO_LONG() { return (int)-2140993789L; }

    static final int PEER_E_INVALID_TIME_PERIOD() { return (int)-2140993787L; }

    static final int PEER_E_CIRCULAR_CHAIN_DETECTED() { return (int)-2140993786L; }

    static final int PEER_E_CERT_STORE_CORRUPTED() { return (int)-2140993535L; }

    static final int PEER_E_NO_CLOUD() { return (int)-2140991487L; }

    static final int PEER_E_CLOUD_NAME_AMBIGUOUS() { return (int)-2140991483L; }

    static final int PEER_E_INVALID_RECORD() { return (int)-2140987376L; }

    static final int PEER_E_NOT_AUTHORIZED() { return (int)-2140987360L; }

    static final int PEER_E_PASSWORD_DOES_NOT_MEET_POLICY() { return (int)-2140987359L; }

    static final int PEER_E_DEFERRED_VALIDATION() { return (int)-2140987344L; }

    static final int PEER_E_INVALID_GROUP_PROPERTIES() { return (int)-2140987328L; }

    static final int PEER_E_INVALID_PEER_NAME() { return (int)-2140987312L; }

    static final int PEER_E_INVALID_CLASSIFIER() { return (int)-2140987296L; }

    static final int PEER_E_INVALID_FRIENDLY_NAME() { return (int)-2140987280L; }

    static final int PEER_E_INVALID_ROLE_PROPERTY() { return (int)-2140987279L; }

    static final int PEER_E_INVALID_CLASSIFIER_PROPERTY() { return (int)-2140987278L; }

    static final int PEER_E_INVALID_RECORD_EXPIRATION() { return (int)-2140987264L; }

    static final int PEER_E_INVALID_CREDENTIAL_INFO() { return (int)-2140987263L; }

    static final int PEER_E_INVALID_CREDENTIAL() { return (int)-2140987262L; }

    static final int PEER_E_INVALID_RECORD_SIZE() { return (int)-2140987261L; }

    static final int PEER_E_UNSUPPORTED_VERSION() { return (int)-2140987248L; }

    static final int PEER_E_GROUP_NOT_READY() { return (int)-2140987247L; }

    static final int PEER_E_GROUP_IN_USE() { return (int)-2140987246L; }

    static final int PEER_E_INVALID_GROUP() { return (int)-2140987245L; }

    static final int PEER_E_NO_MEMBERS_FOUND() { return (int)-2140987244L; }

    static final int PEER_E_NO_MEMBER_CONNECTIONS() { return (int)-2140987243L; }

    static final int PEER_E_UNABLE_TO_LISTEN() { return (int)-2140987242L; }

    static final int PEER_E_IDENTITY_DELETED() { return (int)-2140987232L; }

    static final int PEER_E_SERVICE_NOT_AVAILABLE() { return (int)-2140987231L; }

    static final int PEER_E_CONTACT_NOT_FOUND() { return (int)-2140971007L; }

    static final int PEER_S_GRAPH_DATA_CREATED() { return (int)6488065L; }

    static final int PEER_S_NO_EVENT_DATA() { return (int)6488066L; }

    static final int PEER_S_ALREADY_CONNECTED() { return (int)6496256L; }

    static final int PEER_S_SUBSCRIPTION_EXISTS() { return (int)6512640L; }

    static final int PEER_S_NO_CONNECTIVITY() { return (int)6488069L; }

    static final int PEER_S_ALREADY_A_MEMBER() { return (int)6488070L; }

    static final int PEER_E_CANNOT_CONVERT_PEER_NAME() { return (int)-2140979199L; }

    static final int PEER_E_INVALID_PEER_HOST_NAME() { return (int)-2140979198L; }

    static final int PEER_E_NO_MORE() { return (int)-2140979197L; }

    static final int PEER_E_PNRP_DUPLICATE_PEER_NAME() { return (int)-2140979195L; }

    static final int PEER_E_INVITE_CANCELLED() { return (int)-2140966912L; }

    static final int PEER_E_INVITE_RESPONSE_NOT_AVAILABLE() { return (int)-2140966911L; }

    static final int PEER_E_NOT_SIGNED_IN() { return (int)-2140966909L; }

    static final int PEER_E_PRIVACY_DECLINED() { return (int)-2140966908L; }

    static final int PEER_E_TIMEOUT() { return (int)-2140966907L; }

    static final int PEER_E_INVALID_ADDRESS() { return (int)-2140966905L; }

    static final int PEER_E_FW_EXCEPTION_DISABLED() { return (int)-2140966904L; }

    static final int PEER_E_FW_BLOCKED_BY_POLICY() { return (int)-2140966903L; }

    static final int PEER_E_FW_BLOCKED_BY_SHIELDS_UP() { return (int)-2140966902L; }

    static final int PEER_E_FW_DECLINED() { return (int)-2140966901L; }

    static final int UI_E_CREATE_FAILED() { return (int)-2144731135L; }

    static final int UI_E_SHUTDOWN_CALLED() { return (int)-2144731134L; }

    static final int UI_E_ILLEGAL_REENTRANCY() { return (int)-2144731133L; }

    static final int UI_E_OBJECT_SEALED() { return (int)-2144731132L; }

    static final int UI_E_VALUE_NOT_SET() { return (int)-2144731131L; }

    static final int UI_E_VALUE_NOT_DETERMINED() { return (int)-2144731130L; }

    static final int UI_E_INVALID_OUTPUT() { return (int)-2144731129L; }

    static final int UI_E_BOOLEAN_EXPECTED() { return (int)-2144731128L; }

    static final int UI_E_DIFFERENT_OWNER() { return (int)-2144731127L; }

    static final int UI_E_AMBIGUOUS_MATCH() { return (int)-2144731126L; }

    static final int UI_E_FP_OVERFLOW() { return (int)-2144731125L; }

    static final int UI_E_WRONG_THREAD() { return (int)-2144731124L; }

    static final int UI_E_STORYBOARD_ACTIVE() { return (int)-2144730879L; }

    static final int UI_E_STORYBOARD_NOT_PLAYING() { return (int)-2144730878L; }

    static final int UI_E_START_KEYFRAME_AFTER_END() { return (int)-2144730877L; }

    static final int UI_E_END_KEYFRAME_NOT_DETERMINED() { return (int)-2144730876L; }

    static final int UI_E_LOOPS_OVERLAP() { return (int)-2144730875L; }

    static final int UI_E_TRANSITION_ALREADY_USED() { return (int)-2144730874L; }

    static final int UI_E_TRANSITION_NOT_IN_STORYBOARD() { return (int)-2144730873L; }

    static final int UI_E_TRANSITION_ECLIPSED() { return (int)-2144730872L; }

    static final int UI_E_TIME_BEFORE_LAST_UPDATE() { return (int)-2144730871L; }

    static final int UI_E_TIMER_CLIENT_ALREADY_CONNECTED() { return (int)-2144730870L; }

    static final int UI_E_INVALID_DIMENSION() { return (int)-2144730869L; }

    static final int UI_E_PRIMITIVE_OUT_OF_BOUNDS() { return (int)-2144730868L; }

    static final int UI_E_WINDOW_CLOSED() { return (int)-2144730623L; }

    static final int E_BLUETOOTH_ATT_INVALID_HANDLE() { return (int)-2140864511L; }

    static final int E_BLUETOOTH_ATT_READ_NOT_PERMITTED() { return (int)-2140864510L; }

    static final int E_BLUETOOTH_ATT_WRITE_NOT_PERMITTED() { return (int)-2140864509L; }

    static final int E_BLUETOOTH_ATT_INVALID_PDU() { return (int)-2140864508L; }

    static final int E_BLUETOOTH_ATT_INSUFFICIENT_AUTHENTICATION() { return (int)-2140864507L; }

    static final int E_BLUETOOTH_ATT_REQUEST_NOT_SUPPORTED() { return (int)-2140864506L; }

    static final int E_BLUETOOTH_ATT_INVALID_OFFSET() { return (int)-2140864505L; }

    static final int E_BLUETOOTH_ATT_INSUFFICIENT_AUTHORIZATION() { return (int)-2140864504L; }

    static final int E_BLUETOOTH_ATT_PREPARE_QUEUE_FULL() { return (int)-2140864503L; }

    static final int E_BLUETOOTH_ATT_ATTRIBUTE_NOT_FOUND() { return (int)-2140864502L; }

    static final int E_BLUETOOTH_ATT_ATTRIBUTE_NOT_LONG() { return (int)-2140864501L; }

    static final int E_BLUETOOTH_ATT_INSUFFICIENT_ENCRYPTION_KEY_SIZE() { return (int)-2140864500L; }

    static final int E_BLUETOOTH_ATT_INVALID_ATTRIBUTE_VALUE_LENGTH() { return (int)-2140864499L; }

    static final int E_BLUETOOTH_ATT_UNLIKELY() { return (int)-2140864498L; }

    static final int E_BLUETOOTH_ATT_INSUFFICIENT_ENCRYPTION() { return (int)-2140864497L; }

    static final int E_BLUETOOTH_ATT_UNSUPPORTED_GROUP_TYPE() { return (int)-2140864496L; }

    static final int E_BLUETOOTH_ATT_INSUFFICIENT_RESOURCES() { return (int)-2140864495L; }

    static final int E_BLUETOOTH_ATT_UNKNOWN_ERROR() { return (int)-2140860416L; }

    static final int E_AUDIO_ENGINE_NODE_NOT_FOUND() { return (int)-2140798975L; }

    static final int E_HDAUDIO_EMPTY_CONNECTION_LIST() { return (int)-2140798974L; }

    static final int E_HDAUDIO_CONNECTION_LIST_NOT_SUPPORTED() { return (int)-2140798973L; }

    static final int E_HDAUDIO_NO_LOGICAL_DEVICES_CREATED() { return (int)-2140798972L; }

    static final int E_HDAUDIO_NULL_LINKED_LIST_ENTRY() { return (int)-2140798971L; }

    static final int STATEREPOSITORY_E_CONCURRENCY_LOCKING_FAILURE() { return (int)-2140733439L; }

    static final int STATEREPOSITORY_E_STATEMENT_INPROGRESS() { return (int)-2140733438L; }

    static final int STATEREPOSITORY_E_CONFIGURATION_INVALID() { return (int)-2140733437L; }

    static final int STATEREPOSITORY_E_UNKNOWN_SCHEMA_VERSION() { return (int)-2140733436L; }

    static final int STATEREPOSITORY_ERROR_DICTIONARY_CORRUPTED() { return (int)-2140733435L; }

    static final int STATEREPOSITORY_E_BLOCKED() { return (int)-2140733434L; }

    static final int STATEREPOSITORY_E_BUSY_RETRY() { return (int)-2140733433L; }

    static final int STATEREPOSITORY_E_BUSY_RECOVERY_RETRY() { return (int)-2140733432L; }

    static final int STATEREPOSITORY_E_LOCKED_RETRY() { return (int)-2140733431L; }

    static final int STATEREPOSITORY_E_LOCKED_SHAREDCACHE_RETRY() { return (int)-2140733430L; }

    static final int STATEREPOSITORY_E_TRANSACTION_REQUIRED() { return (int)-2140733429L; }

    static final int STATEREPOSITORY_E_BUSY_TIMEOUT_EXCEEDED() { return (int)-2140733428L; }

    static final int STATEREPOSITORY_E_BUSY_RECOVERY_TIMEOUT_EXCEEDED() { return (int)-2140733427L; }

    static final int STATEREPOSITORY_E_LOCKED_TIMEOUT_EXCEEDED() { return (int)-2140733426L; }

    static final int STATEREPOSITORY_E_LOCKED_SHAREDCACHE_TIMEOUT_EXCEEDED() { return (int)-2140733425L; }

    static final int STATEREPOSITORY_E_SERVICE_STOP_IN_PROGRESS() { return (int)-2140733424L; }

    static final int STATEREPOSTORY_E_NESTED_TRANSACTION_NOT_SUPPORTED() { return (int)-2140733423L; }

    static final int STATEREPOSITORY_ERROR_CACHE_CORRUPTED() { return (int)-2140733422L; }

    static final int STATEREPOSITORY_TRANSACTION_CALLER_ID_CHANGED() { return (int)6750227L; }

    static final int STATEREPOSITORY_TRANSACTION_IN_PROGRESS() { return (int)6750228L; }

    static final int ERROR_SPACES_POOL_WAS_DELETED() { return (int)15138817L; }

    static final int ERROR_SPACES_FAULT_DOMAIN_TYPE_INVALID() { return (int)-2132344831L; }

    static final int ERROR_SPACES_INTERNAL_ERROR() { return (int)-2132344830L; }

    static final int ERROR_SPACES_RESILIENCY_TYPE_INVALID() { return (int)-2132344829L; }

    static final int ERROR_SPACES_DRIVE_SECTOR_SIZE_INVALID() { return (int)-2132344828L; }

    static final int ERROR_SPACES_DRIVE_REDUNDANCY_INVALID() { return (int)-2132344826L; }

    static final int ERROR_SPACES_NUMBER_OF_DATA_COPIES_INVALID() { return (int)-2132344825L; }

    static final int ERROR_SPACES_PARITY_LAYOUT_INVALID() { return (int)-2132344824L; }

    static final int ERROR_SPACES_INTERLEAVE_LENGTH_INVALID() { return (int)-2132344823L; }

    static final int ERROR_SPACES_NUMBER_OF_COLUMNS_INVALID() { return (int)-2132344822L; }

    static final int ERROR_SPACES_NOT_ENOUGH_DRIVES() { return (int)-2132344821L; }

    static final int ERROR_SPACES_EXTENDED_ERROR() { return (int)-2132344820L; }

    static final int ERROR_SPACES_PROVISIONING_TYPE_INVALID() { return (int)-2132344819L; }

    static final int ERROR_SPACES_ALLOCATION_SIZE_INVALID() { return (int)-2132344818L; }

    static final int ERROR_SPACES_ENCLOSURE_AWARE_INVALID() { return (int)-2132344817L; }

    static final int ERROR_SPACES_WRITE_CACHE_SIZE_INVALID() { return (int)-2132344816L; }

    static final int ERROR_SPACES_NUMBER_OF_GROUPS_INVALID() { return (int)-2132344815L; }

    static final int ERROR_SPACES_DRIVE_OPERATIONAL_STATE_INVALID() { return (int)-2132344814L; }

    static final int ERROR_SPACES_ENTRY_INCOMPLETE() { return (int)-2132344813L; }

    static final int ERROR_SPACES_ENTRY_INVALID() { return (int)-2132344812L; }

    static final int ERROR_VOLSNAP_BOOTFILE_NOT_VALID() { return (int)-2138963967L; }

    static final int ERROR_VOLSNAP_ACTIVATION_TIMEOUT() { return (int)-2138963966L; }

    static final int ERROR_TIERING_NOT_SUPPORTED_ON_VOLUME() { return (int)-2138898431L; }

    static final int ERROR_TIERING_VOLUME_DISMOUNT_IN_PROGRESS() { return (int)-2138898430L; }

    static final int ERROR_TIERING_STORAGE_TIER_NOT_FOUND() { return (int)-2138898429L; }

    static final int ERROR_TIERING_INVALID_FILE_ID() { return (int)-2138898428L; }

    static final int ERROR_TIERING_WRONG_CLUSTER_NODE() { return (int)-2138898427L; }

    static final int ERROR_TIERING_ALREADY_PROCESSING() { return (int)-2138898426L; }

    static final int ERROR_TIERING_CANNOT_PIN_OBJECT() { return (int)-2138898425L; }

    static final int ERROR_TIERING_FILE_IS_NOT_PINNED() { return (int)-2138898424L; }

    static final int ERROR_NOT_A_TIERED_VOLUME() { return (int)-2138898423L; }

    static final int ERROR_ATTRIBUTE_NOT_PRESENT() { return (int)-2138898422L; }

    static final int ERROR_SECCORE_INVALID_COMMAND() { return (int)-1058537472L; }

    static final int ERROR_NO_APPLICABLE_APP_LICENSES_FOUND() { return (int)-1058406399L; }

    static final int ERROR_CLIP_LICENSE_NOT_FOUND() { return (int)-1058406398L; }

    static final int ERROR_CLIP_DEVICE_LICENSE_MISSING() { return (int)-1058406397L; }

    static final int ERROR_CLIP_LICENSE_INVALID_SIGNATURE() { return (int)-1058406396L; }

    static final int ERROR_CLIP_KEYHOLDER_LICENSE_MISSING_OR_INVALID() { return (int)-1058406395L; }

    static final int ERROR_CLIP_LICENSE_EXPIRED() { return (int)-1058406394L; }

    static final int ERROR_CLIP_LICENSE_SIGNED_BY_UNKNOWN_SOURCE() { return (int)-1058406393L; }

    static final int ERROR_CLIP_LICENSE_NOT_SIGNED() { return (int)-1058406392L; }

    static final int ERROR_CLIP_LICENSE_HARDWARE_ID_OUT_OF_TOLERANCE() { return (int)-1058406391L; }

    static final int ERROR_CLIP_LICENSE_DEVICE_ID_MISMATCH() { return (int)-1058406390L; }

    static final int DXGI_STATUS_OCCLUDED() { return (int)142213121L; }

    static final int DXGI_STATUS_CLIPPED() { return (int)142213122L; }

    static final int DXGI_STATUS_NO_REDIRECTION() { return (int)142213124L; }

    static final int DXGI_STATUS_NO_DESKTOP_ACCESS() { return (int)142213125L; }

    static final int DXGI_STATUS_GRAPHICS_VIDPN_SOURCE_IN_USE() { return (int)142213126L; }

    static final int DXGI_STATUS_MODE_CHANGED() { return (int)142213127L; }

    static final int DXGI_STATUS_MODE_CHANGE_IN_PROGRESS() { return (int)142213128L; }

    static final int DXGI_ERROR_INVALID_CALL() { return (int)-2005270527L; }

    static final int DXGI_ERROR_NOT_FOUND() { return (int)-2005270526L; }

    static final int DXGI_ERROR_MORE_DATA() { return (int)-2005270525L; }

    static final int DXGI_ERROR_UNSUPPORTED() { return (int)-2005270524L; }

    static final int DXGI_ERROR_DEVICE_REMOVED() { return (int)-2005270523L; }

    static final int DXGI_ERROR_DEVICE_HUNG() { return (int)-2005270522L; }

    static final int DXGI_ERROR_DEVICE_RESET() { return (int)-2005270521L; }

    static final int DXGI_ERROR_WAS_STILL_DRAWING() { return (int)-2005270518L; }

    static final int DXGI_ERROR_FRAME_STATISTICS_DISJOINT() { return (int)-2005270517L; }

    static final int DXGI_ERROR_GRAPHICS_VIDPN_SOURCE_IN_USE() { return (int)-2005270516L; }

    static final int DXGI_ERROR_DRIVER_INTERNAL_ERROR() { return (int)-2005270496L; }

    static final int DXGI_ERROR_NONEXCLUSIVE() { return (int)-2005270495L; }

    static final int DXGI_ERROR_NOT_CURRENTLY_AVAILABLE() { return (int)-2005270494L; }

    static final int DXGI_ERROR_REMOTE_CLIENT_DISCONNECTED() { return (int)-2005270493L; }

    static final int DXGI_ERROR_REMOTE_OUTOFMEMORY() { return (int)-2005270492L; }

    static final int DXGI_ERROR_ACCESS_LOST() { return (int)-2005270490L; }

    static final int DXGI_ERROR_WAIT_TIMEOUT() { return (int)-2005270489L; }

    static final int DXGI_ERROR_SESSION_DISCONNECTED() { return (int)-2005270488L; }

    static final int DXGI_ERROR_RESTRICT_TO_OUTPUT_STALE() { return (int)-2005270487L; }

    static final int DXGI_ERROR_CANNOT_PROTECT_CONTENT() { return (int)-2005270486L; }

    static final int DXGI_ERROR_ACCESS_DENIED() { return (int)-2005270485L; }

    static final int DXGI_ERROR_NAME_ALREADY_EXISTS() { return (int)-2005270484L; }

    static final int DXGI_ERROR_SDK_COMPONENT_MISSING() { return (int)-2005270483L; }

    static final int DXGI_ERROR_NOT_CURRENT() { return (int)-2005270482L; }

    static final int DXGI_ERROR_HW_PROTECTION_OUTOFMEMORY() { return (int)-2005270480L; }

    static final int DXGI_ERROR_DYNAMIC_CODE_POLICY_VIOLATION() { return (int)-2005270479L; }

    static final int DXGI_ERROR_NON_COMPOSITED_UI() { return (int)-2005270478L; }

    static final int DXCORE_ERROR_EVENT_NOT_UNREGISTERED() { return (int)-2004877311L; }

    static final int DXGI_STATUS_UNOCCLUDED() { return (int)142213129L; }

    static final int DXGI_STATUS_DDA_WAS_STILL_DRAWING() { return (int)142213130L; }

    static final int DXGI_ERROR_MODE_CHANGE_IN_PROGRESS() { return (int)-2005270491L; }

    static final int DXGI_STATUS_PRESENT_REQUIRED() { return (int)142213167L; }

    static final int DXGI_ERROR_CACHE_CORRUPT() { return (int)-2005270477L; }

    static final int DXGI_ERROR_CACHE_FULL() { return (int)-2005270476L; }

    static final int DXGI_ERROR_CACHE_HASH_COLLISION() { return (int)-2005270475L; }

    static final int DXGI_ERROR_ALREADY_EXISTS() { return (int)-2005270474L; }

    static final int DXGI_DDI_ERR_WASSTILLDRAWING() { return (int)-2005204991L; }

    static final int DXGI_DDI_ERR_UNSUPPORTED() { return (int)-2005204990L; }

    static final int DXGI_DDI_ERR_NONEXCLUSIVE() { return (int)-2005204989L; }

    static final int D3D10_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS() { return (int)-2005336063L; }

    static final int D3D10_ERROR_FILE_NOT_FOUND() { return (int)-2005336062L; }

    static final int D3D11_ERROR_TOO_MANY_UNIQUE_STATE_OBJECTS() { return (int)-2005139455L; }

    static final int D3D11_ERROR_FILE_NOT_FOUND() { return (int)-2005139454L; }

    static final int D3D11_ERROR_TOO_MANY_UNIQUE_VIEW_OBJECTS() { return (int)-2005139453L; }

    static final int D3D11_ERROR_DEFERRED_CONTEXT_MAP_WITHOUT_INITIAL_DISCARD() { return (int)-2005139452L; }

    static final int D3D12_ERROR_ADAPTER_NOT_FOUND() { return (int)-2005008383L; }

    static final int D3D12_ERROR_DRIVER_VERSION_MISMATCH() { return (int)-2005008382L; }

    static final int D2DERR_WRONG_STATE() { return (int)-2003238911L; }

    static final int D2DERR_NOT_INITIALIZED() { return (int)-2003238910L; }

    static final int D2DERR_UNSUPPORTED_OPERATION() { return (int)-2003238909L; }

    static final int D2DERR_SCANNER_FAILED() { return (int)-2003238908L; }

    static final int D2DERR_SCREEN_ACCESS_DENIED() { return (int)-2003238907L; }

    static final int D2DERR_DISPLAY_STATE_INVALID() { return (int)-2003238906L; }

    static final int D2DERR_ZERO_VECTOR() { return (int)-2003238905L; }

    static final int D2DERR_INTERNAL_ERROR() { return (int)-2003238904L; }

    static final int D2DERR_DISPLAY_FORMAT_NOT_SUPPORTED() { return (int)-2003238903L; }

    static final int D2DERR_INVALID_CALL() { return (int)-2003238902L; }

    static final int D2DERR_NO_HARDWARE_DEVICE() { return (int)-2003238901L; }

    static final int D2DERR_RECREATE_TARGET() { return (int)-2003238900L; }

    static final int D2DERR_TOO_MANY_SHADER_ELEMENTS() { return (int)-2003238899L; }

    static final int D2DERR_SHADER_COMPILE_FAILED() { return (int)-2003238898L; }

    static final int D2DERR_MAX_TEXTURE_SIZE_EXCEEDED() { return (int)-2003238897L; }

    static final int D2DERR_UNSUPPORTED_VERSION() { return (int)-2003238896L; }

    static final int D2DERR_BAD_NUMBER() { return (int)-2003238895L; }

    static final int D2DERR_WRONG_FACTORY() { return (int)-2003238894L; }

    static final int D2DERR_LAYER_ALREADY_IN_USE() { return (int)-2003238893L; }

    static final int D2DERR_POP_CALL_DID_NOT_MATCH_PUSH() { return (int)-2003238892L; }

    static final int D2DERR_WRONG_RESOURCE_DOMAIN() { return (int)-2003238891L; }

    static final int D2DERR_PUSH_POP_UNBALANCED() { return (int)-2003238890L; }

    static final int D2DERR_RENDER_TARGET_HAS_LAYER_OR_CLIPRECT() { return (int)-2003238889L; }

    static final int D2DERR_INCOMPATIBLE_BRUSH_TYPES() { return (int)-2003238888L; }

    static final int D2DERR_WIN32_ERROR() { return (int)-2003238887L; }

    static final int D2DERR_TARGET_NOT_GDI_COMPATIBLE() { return (int)-2003238886L; }

    static final int D2DERR_TEXT_EFFECT_IS_WRONG_TYPE() { return (int)-2003238885L; }

    static final int D2DERR_TEXT_RENDERER_NOT_RELEASED() { return (int)-2003238884L; }

    static final int D2DERR_EXCEEDS_MAX_BITMAP_SIZE() { return (int)-2003238883L; }

    static final int D2DERR_INVALID_GRAPH_CONFIGURATION() { return (int)-2003238882L; }

    static final int D2DERR_INVALID_INTERNAL_GRAPH_CONFIGURATION() { return (int)-2003238881L; }

    static final int D2DERR_CYCLIC_GRAPH() { return (int)-2003238880L; }

    static final int D2DERR_BITMAP_CANNOT_DRAW() { return (int)-2003238879L; }

    static final int D2DERR_OUTSTANDING_BITMAP_REFERENCES() { return (int)-2003238878L; }

    static final int D2DERR_ORIGINAL_TARGET_NOT_BOUND() { return (int)-2003238877L; }

    static final int D2DERR_INVALID_TARGET() { return (int)-2003238876L; }

    static final int D2DERR_BITMAP_BOUND_AS_TARGET() { return (int)-2003238875L; }

    static final int D2DERR_INSUFFICIENT_DEVICE_CAPABILITIES() { return (int)-2003238874L; }

    static final int D2DERR_INTERMEDIATE_TOO_LARGE() { return (int)-2003238873L; }

    static final int D2DERR_EFFECT_IS_NOT_REGISTERED() { return (int)-2003238872L; }

    static final int D2DERR_INVALID_PROPERTY() { return (int)-2003238871L; }

    static final int D2DERR_NO_SUBPROPERTIES() { return (int)-2003238870L; }

    static final int D2DERR_PRINT_JOB_CLOSED() { return (int)-2003238869L; }

    static final int D2DERR_PRINT_FORMAT_NOT_SUPPORTED() { return (int)-2003238868L; }

    static final int D2DERR_TOO_MANY_TRANSFORM_INPUTS() { return (int)-2003238867L; }

    static final int D2DERR_INVALID_GLYPH_IMAGE() { return (int)-2003238866L; }

    static final int DWRITE_E_FILEFORMAT() { return (int)-2003283968L; }

    static final int DWRITE_E_UNEXPECTED() { return (int)-2003283967L; }

    static final int DWRITE_E_NOFONT() { return (int)-2003283966L; }

    static final int DWRITE_E_FILENOTFOUND() { return (int)-2003283965L; }

    static final int DWRITE_E_FILEACCESS() { return (int)-2003283964L; }

    static final int DWRITE_E_FONTCOLLECTIONOBSOLETE() { return (int)-2003283963L; }

    static final int DWRITE_E_ALREADYREGISTERED() { return (int)-2003283962L; }

    static final int DWRITE_E_CACHEFORMAT() { return (int)-2003283961L; }

    static final int DWRITE_E_CACHEVERSION() { return (int)-2003283960L; }

    static final int DWRITE_E_UNSUPPORTEDOPERATION() { return (int)-2003283959L; }

    static final int DWRITE_E_TEXTRENDERERINCOMPATIBLE() { return (int)-2003283958L; }

    static final int DWRITE_E_FLOWDIRECTIONCONFLICTS() { return (int)-2003283957L; }

    static final int DWRITE_E_NOCOLOR() { return (int)-2003283956L; }

    static final int DWRITE_E_REMOTEFONT() { return (int)-2003283955L; }

    static final int DWRITE_E_DOWNLOADCANCELLED() { return (int)-2003283954L; }

    static final int DWRITE_E_DOWNLOADFAILED() { return (int)-2003283953L; }

    static final int DWRITE_E_TOOMANYDOWNLOADS() { return (int)-2003283952L; }

    static final int WINCODEC_ERR_WRONGSTATE() { return (int)-2003292412L; }

    static final int WINCODEC_ERR_VALUEOUTOFRANGE() { return (int)-2003292411L; }

    static final int WINCODEC_ERR_UNKNOWNIMAGEFORMAT() { return (int)-2003292409L; }

    static final int WINCODEC_ERR_UNSUPPORTEDVERSION() { return (int)-2003292405L; }

    static final int WINCODEC_ERR_NOTINITIALIZED() { return (int)-2003292404L; }

    static final int WINCODEC_ERR_ALREADYLOCKED() { return (int)-2003292403L; }

    static final int WINCODEC_ERR_PROPERTYNOTFOUND() { return (int)-2003292352L; }

    static final int WINCODEC_ERR_PROPERTYNOTSUPPORTED() { return (int)-2003292351L; }

    static final int WINCODEC_ERR_PROPERTYSIZE() { return (int)-2003292350L; }

    static final int WINCODEC_ERR_CODECPRESENT() { return (int)-2003292349L; }

    static final int WINCODEC_ERR_CODECNOTHUMBNAIL() { return (int)-2003292348L; }

    static final int WINCODEC_ERR_PALETTEUNAVAILABLE() { return (int)-2003292347L; }

    static final int WINCODEC_ERR_CODECTOOMANYSCANLINES() { return (int)-2003292346L; }

    static final int WINCODEC_ERR_INTERNALERROR() { return (int)-2003292344L; }

    static final int WINCODEC_ERR_SOURCERECTDOESNOTMATCHDIMENSIONS() { return (int)-2003292343L; }

    static final int WINCODEC_ERR_COMPONENTNOTFOUND() { return (int)-2003292336L; }

    static final int WINCODEC_ERR_IMAGESIZEOUTOFRANGE() { return (int)-2003292335L; }

    static final int WINCODEC_ERR_TOOMUCHMETADATA() { return (int)-2003292334L; }

    static final int WINCODEC_ERR_BADIMAGE() { return (int)-2003292320L; }

    static final int WINCODEC_ERR_BADHEADER() { return (int)-2003292319L; }

    static final int WINCODEC_ERR_FRAMEMISSING() { return (int)-2003292318L; }

    static final int WINCODEC_ERR_BADMETADATAHEADER() { return (int)-2003292317L; }

    static final int WINCODEC_ERR_BADSTREAMDATA() { return (int)-2003292304L; }

    static final int WINCODEC_ERR_STREAMWRITE() { return (int)-2003292303L; }

    static final int WINCODEC_ERR_STREAMREAD() { return (int)-2003292302L; }

    static final int WINCODEC_ERR_STREAMNOTAVAILABLE() { return (int)-2003292301L; }

    static final int WINCODEC_ERR_UNSUPPORTEDPIXELFORMAT() { return (int)-2003292288L; }

    static final int WINCODEC_ERR_UNSUPPORTEDOPERATION() { return (int)-2003292287L; }

    static final int WINCODEC_ERR_INVALIDREGISTRATION() { return (int)-2003292278L; }

    static final int WINCODEC_ERR_COMPONENTINITIALIZEFAILURE() { return (int)-2003292277L; }

    static final int WINCODEC_ERR_INSUFFICIENTBUFFER() { return (int)-2003292276L; }

    static final int WINCODEC_ERR_DUPLICATEMETADATAPRESENT() { return (int)-2003292275L; }

    static final int WINCODEC_ERR_PROPERTYUNEXPECTEDTYPE() { return (int)-2003292274L; }

    static final int WINCODEC_ERR_UNEXPECTEDSIZE() { return (int)-2003292273L; }

    static final int WINCODEC_ERR_INVALIDQUERYREQUEST() { return (int)-2003292272L; }

    static final int WINCODEC_ERR_UNEXPECTEDMETADATATYPE() { return (int)-2003292271L; }

    static final int WINCODEC_ERR_REQUESTONLYVALIDATMETADATAROOT() { return (int)-2003292270L; }

    static final int WINCODEC_ERR_INVALIDQUERYCHARACTER() { return (int)-2003292269L; }

    static final int WINCODEC_ERR_WIN32ERROR() { return (int)-2003292268L; }

    static final int WINCODEC_ERR_INVALIDPROGRESSIVELEVEL() { return (int)-2003292267L; }

    static final int WINCODEC_ERR_INVALIDJPEGSCANINDEX() { return (int)-2003292266L; }

    static final int MILERR_OBJECTBUSY() { return (int)-2003304447L; }

    static final int MILERR_INSUFFICIENTBUFFER() { return (int)-2003304446L; }

    static final int MILERR_WIN32ERROR() { return (int)-2003304445L; }

    static final int MILERR_SCANNER_FAILED() { return (int)-2003304444L; }

    static final int MILERR_SCREENACCESSDENIED() { return (int)-2003304443L; }

    static final int MILERR_DISPLAYSTATEINVALID() { return (int)-2003304442L; }

    static final int MILERR_NONINVERTIBLEMATRIX() { return (int)-2003304441L; }

    static final int MILERR_ZEROVECTOR() { return (int)-2003304440L; }

    static final int MILERR_TERMINATED() { return (int)-2003304439L; }

    static final int MILERR_BADNUMBER() { return (int)-2003304438L; }

    static final int MILERR_INTERNALERROR() { return (int)-2003304320L; }

    static final int MILERR_DISPLAYFORMATNOTSUPPORTED() { return (int)-2003304316L; }

    static final int MILERR_INVALIDCALL() { return (int)-2003304315L; }

    static final int MILERR_ALREADYLOCKED() { return (int)-2003304314L; }

    static final int MILERR_NOTLOCKED() { return (int)-2003304313L; }

    static final int MILERR_DEVICECANNOTRENDERTEXT() { return (int)-2003304312L; }

    static final int MILERR_GLYPHBITMAPMISSED() { return (int)-2003304311L; }

    static final int MILERR_MALFORMEDGLYPHCACHE() { return (int)-2003304310L; }

    static final int MILERR_GENERIC_IGNORE() { return (int)-2003304309L; }

    static final int MILERR_MALFORMED_GUIDELINE_DATA() { return (int)-2003304308L; }

    static final int MILERR_NO_HARDWARE_DEVICE() { return (int)-2003304307L; }

    static final int MILERR_NEED_RECREATE_AND_PRESENT() { return (int)-2003304306L; }

    static final int MILERR_ALREADY_INITIALIZED() { return (int)-2003304305L; }

    static final int MILERR_MISMATCHED_SIZE() { return (int)-2003304304L; }

    static final int MILERR_NO_REDIRECTION_SURFACE_AVAILABLE() { return (int)-2003304303L; }

    static final int MILERR_REMOTING_NOT_SUPPORTED() { return (int)-2003304302L; }

    static final int MILERR_QUEUED_PRESENT_NOT_SUPPORTED() { return (int)-2003304301L; }

    static final int MILERR_NOT_QUEUING_PRESENTS() { return (int)-2003304300L; }

    static final int MILERR_NO_REDIRECTION_SURFACE_RETRY_LATER() { return (int)-2003304299L; }

    static final int MILERR_TOOMANYSHADERELEMNTS() { return (int)-2003304298L; }

    static final int MILERR_MROW_READLOCK_FAILED() { return (int)-2003304297L; }

    static final int MILERR_MROW_UPDATE_FAILED() { return (int)-2003304296L; }

    static final int MILERR_SHADER_COMPILE_FAILED() { return (int)-2003304295L; }

    static final int MILERR_MAX_TEXTURE_SIZE_EXCEEDED() { return (int)-2003304294L; }

    static final int MILERR_QPC_TIME_WENT_BACKWARD() { return (int)-2003304293L; }

    static final int MILERR_DXGI_ENUMERATION_OUT_OF_SYNC() { return (int)-2003304291L; }

    static final int MILERR_ADAPTER_NOT_FOUND() { return (int)-2003304290L; }

    static final int MILERR_COLORSPACE_NOT_SUPPORTED() { return (int)-2003304289L; }

    static final int MILERR_PREFILTER_NOT_SUPPORTED() { return (int)-2003304288L; }

    static final int MILERR_DISPLAYID_ACCESS_DENIED() { return (int)-2003304287L; }

    static final int UCEERR_INVALIDPACKETHEADER() { return (int)-2003303424L; }

    static final int UCEERR_UNKNOWNPACKET() { return (int)-2003303423L; }

    static final int UCEERR_ILLEGALPACKET() { return (int)-2003303422L; }

    static final int UCEERR_MALFORMEDPACKET() { return (int)-2003303421L; }

    static final int UCEERR_ILLEGALHANDLE() { return (int)-2003303420L; }

    static final int UCEERR_HANDLELOOKUPFAILED() { return (int)-2003303419L; }

    static final int UCEERR_RENDERTHREADFAILURE() { return (int)-2003303418L; }

    static final int UCEERR_CTXSTACKFRSTTARGETNULL() { return (int)-2003303417L; }

    static final int UCEERR_CONNECTIONIDLOOKUPFAILED() { return (int)-2003303416L; }

    static final int UCEERR_BLOCKSFULL() { return (int)-2003303415L; }

    static final int UCEERR_MEMORYFAILURE() { return (int)-2003303414L; }

    static final int UCEERR_PACKETRECORDOUTOFRANGE() { return (int)-2003303413L; }

    static final int UCEERR_ILLEGALRECORDTYPE() { return (int)-2003303412L; }

    static final int UCEERR_OUTOFHANDLES() { return (int)-2003303411L; }

    static final int UCEERR_UNCHANGABLE_UPDATE_ATTEMPTED() { return (int)-2003303410L; }

    static final int UCEERR_NO_MULTIPLE_WORKER_THREADS() { return (int)-2003303409L; }

    static final int UCEERR_REMOTINGNOTSUPPORTED() { return (int)-2003303408L; }

    static final int UCEERR_MISSINGENDCOMMAND() { return (int)-2003303407L; }

    static final int UCEERR_MISSINGBEGINCOMMAND() { return (int)-2003303406L; }

    static final int UCEERR_CHANNELSYNCTIMEDOUT() { return (int)-2003303405L; }

    static final int UCEERR_CHANNELSYNCABANDONED() { return (int)-2003303404L; }

    static final int UCEERR_UNSUPPORTEDTRANSPORTVERSION() { return (int)-2003303403L; }

    static final int UCEERR_TRANSPORTUNAVAILABLE() { return (int)-2003303402L; }

    static final int UCEERR_FEEDBACK_UNSUPPORTED() { return (int)-2003303401L; }

    static final int UCEERR_COMMANDTRANSPORTDENIED() { return (int)-2003303400L; }

    static final int UCEERR_GRAPHICSSTREAMUNAVAILABLE() { return (int)-2003303399L; }

    static final int UCEERR_GRAPHICSSTREAMALREADYOPEN() { return (int)-2003303392L; }

    static final int UCEERR_TRANSPORTDISCONNECTED() { return (int)-2003303391L; }

    static final int UCEERR_TRANSPORTOVERLOADED() { return (int)-2003303390L; }

    static final int UCEERR_PARTITION_ZOMBIED() { return (int)-2003303389L; }

    static final int MILAVERR_NOCLOCK() { return (int)-2003303168L; }

    static final int MILAVERR_NOMEDIATYPE() { return (int)-2003303167L; }

    static final int MILAVERR_NOVIDEOMIXER() { return (int)-2003303166L; }

    static final int MILAVERR_NOVIDEOPRESENTER() { return (int)-2003303165L; }

    static final int MILAVERR_NOREADYFRAMES() { return (int)-2003303164L; }

    static final int MILAVERR_MODULENOTLOADED() { return (int)-2003303163L; }

    static final int MILAVERR_WMPFACTORYNOTREGISTERED() { return (int)-2003303162L; }

    static final int MILAVERR_INVALIDWMPVERSION() { return (int)-2003303161L; }

    static final int MILAVERR_INSUFFICIENTVIDEORESOURCES() { return (int)-2003303160L; }

    static final int MILAVERR_VIDEOACCELERATIONNOTAVAILABLE() { return (int)-2003303159L; }

    static final int MILAVERR_REQUESTEDTEXTURETOOBIG() { return (int)-2003303158L; }

    static final int MILAVERR_SEEKFAILED() { return (int)-2003303157L; }

    static final int MILAVERR_UNEXPECTEDWMPFAILURE() { return (int)-2003303156L; }

    static final int MILAVERR_MEDIAPLAYERCLOSED() { return (int)-2003303155L; }

    static final int MILAVERR_UNKNOWNHARDWAREERROR() { return (int)-2003303154L; }

    static final int MILEFFECTSERR_UNKNOWNPROPERTY() { return (int)-2003302898L; }

    static final int MILEFFECTSERR_EFFECTNOTPARTOFGROUP() { return (int)-2003302897L; }

    static final int MILEFFECTSERR_NOINPUTSOURCEATTACHED() { return (int)-2003302896L; }

    static final int MILEFFECTSERR_CONNECTORNOTCONNECTED() { return (int)-2003302895L; }

    static final int MILEFFECTSERR_CONNECTORNOTASSOCIATEDWITHEFFECT() { return (int)-2003302894L; }

    static final int MILEFFECTSERR_RESERVED() { return (int)-2003302893L; }

    static final int MILEFFECTSERR_CYCLEDETECTED() { return (int)-2003302892L; }

    static final int MILEFFECTSERR_EFFECTINMORETHANONEGRAPH() { return (int)-2003302891L; }

    static final int MILEFFECTSERR_EFFECTALREADYINAGRAPH() { return (int)-2003302890L; }

    static final int MILEFFECTSERR_EFFECTHASNOCHILDREN() { return (int)-2003302889L; }

    static final int MILEFFECTSERR_ALREADYATTACHEDTOLISTENER() { return (int)-2003302888L; }

    static final int MILEFFECTSERR_NOTAFFINETRANSFORM() { return (int)-2003302887L; }

    static final int MILEFFECTSERR_EMPTYBOUNDS() { return (int)-2003302886L; }

    static final int MILEFFECTSERR_OUTPUTSIZETOOLARGE() { return (int)-2003302885L; }

    static final int DWMERR_STATE_TRANSITION_FAILED() { return (int)-2003302656L; }

    static final int DWMERR_THEME_FAILED() { return (int)-2003302655L; }

    static final int DWMERR_CATASTROPHIC_FAILURE() { return (int)-2003302654L; }

    static final int DCOMPOSITION_ERROR_WINDOW_ALREADY_COMPOSED() { return (int)-2003302400L; }

    static final int DCOMPOSITION_ERROR_SURFACE_BEING_RENDERED() { return (int)-2003302399L; }

    static final int DCOMPOSITION_ERROR_SURFACE_NOT_BEING_RENDERED() { return (int)-2003302398L; }

    static final int ONL_E_INVALID_AUTHENTICATION_TARGET() { return (int)-2138701823L; }

    static final int ONL_E_ACCESS_DENIED_BY_TOU() { return (int)-2138701822L; }

    static final int ONL_E_INVALID_APPLICATION() { return (int)-2138701821L; }

    static final int ONL_E_PASSWORD_UPDATE_REQUIRED() { return (int)-2138701820L; }

    static final int ONL_E_ACCOUNT_UPDATE_REQUIRED() { return (int)-2138701819L; }

    static final int ONL_E_FORCESIGNIN() { return (int)-2138701818L; }

    static final int ONL_E_ACCOUNT_LOCKED() { return (int)-2138701817L; }

    static final int ONL_E_PARENTAL_CONSENT_REQUIRED() { return (int)-2138701816L; }

    static final int ONL_E_EMAIL_VERIFICATION_REQUIRED() { return (int)-2138701815L; }

    static final int ONL_E_ACCOUNT_SUSPENDED_COMPROIMISE() { return (int)-2138701814L; }

    static final int ONL_E_ACCOUNT_SUSPENDED_ABUSE() { return (int)-2138701813L; }

    static final int ONL_E_ACTION_REQUIRED() { return (int)-2138701812L; }

    static final int ONL_CONNECTION_COUNT_LIMIT() { return (int)-2138701811L; }

    static final int ONL_E_CONNECTED_ACCOUNT_CAN_NOT_SIGNOUT() { return (int)-2138701810L; }

    static final int ONL_E_USER_AUTHENTICATION_REQUIRED() { return (int)-2138701809L; }

    static final int ONL_E_REQUEST_THROTTLED() { return (int)-2138701808L; }

    static final int FA_E_MAX_PERSISTED_ITEMS_REACHED() { return (int)-2144927200L; }

    static final int FA_E_HOMEGROUP_NOT_AVAILABLE() { return (int)-2144927198L; }

    static final int E_MONITOR_RESOLUTION_TOO_LOW() { return (int)-2144927152L; }

    static final int E_ELEVATED_ACTIVATION_NOT_SUPPORTED() { return (int)-2144927151L; }

    static final int E_UAC_DISABLED() { return (int)-2144927150L; }

    static final int E_FULL_ADMIN_NOT_SUPPORTED() { return (int)-2144927149L; }

    static final int E_APPLICATION_NOT_REGISTERED() { return (int)-2144927148L; }

    static final int E_MULTIPLE_EXTENSIONS_FOR_APPLICATION() { return (int)-2144927147L; }

    static final int E_MULTIPLE_PACKAGES_FOR_FAMILY() { return (int)-2144927146L; }

    static final int E_APPLICATION_MANAGER_NOT_RUNNING() { return (int)-2144927145L; }

    static final int S_STORE_LAUNCHED_FOR_REMEDIATION() { return (int)2556504L; }

}

