// Generated by jextract

package com.github.tornaia.cf.win.processenv;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import jdk.incubator.foreign.*;
import jdk.incubator.foreign.MemoryLayout.PathElement;
import static jdk.incubator.foreign.CLinker.*;
class processenv_h$41 extends processenv_h$40 {

    /* package-private */ processenv_h$41() {}
    public static @C("int") int Uri_ENCODING_RFC() {
        return processenv_h$constants$112.Uri_ENCODING_RFC();
    }
    public static @C("int") int PARSE_ENCODE() {
        return processenv_h$constants$112.PARSE_ENCODE();
    }
    public static @C("int") int PARSE_DECODE() {
        return processenv_h$constants$112.PARSE_DECODE();
    }
    public static @C("long") int INET_E_USE_DEFAULT_PROTOCOLHANDLER() {
        return processenv_h$constants$112.INET_E_USE_DEFAULT_PROTOCOLHANDLER();
    }
    public static @C("long") int INET_E_USE_DEFAULT_SETTING() {
        return processenv_h$constants$112.INET_E_USE_DEFAULT_SETTING();
    }
    public static @C("long") int INET_E_DEFAULT_ACTION() {
        return processenv_h$constants$112.INET_E_DEFAULT_ACTION();
    }
    public static @C("long") int INET_E_QUERYOPTION_UNKNOWN() {
        return processenv_h$constants$112.INET_E_QUERYOPTION_UNKNOWN();
    }
    public static @C("long") int INET_E_REDIRECTING() {
        return processenv_h$constants$112.INET_E_REDIRECTING();
    }
    public static @C("long") int PIDDI_THUMBNAIL() {
        return processenv_h$constants$112.PIDDI_THUMBNAIL();
    }
    public static @C("long") int PIDSI_TITLE() {
        return processenv_h$constants$112.PIDSI_TITLE();
    }
    public static @C("long") int PIDSI_SUBJECT() {
        return processenv_h$constants$112.PIDSI_SUBJECT();
    }
    public static @C("long") int PIDSI_AUTHOR() {
        return processenv_h$constants$112.PIDSI_AUTHOR();
    }
    public static @C("long") int PIDSI_KEYWORDS() {
        return processenv_h$constants$112.PIDSI_KEYWORDS();
    }
    public static @C("long") int PIDSI_COMMENTS() {
        return processenv_h$constants$112.PIDSI_COMMENTS();
    }
    public static @C("long") int PIDSI_TEMPLATE() {
        return processenv_h$constants$112.PIDSI_TEMPLATE();
    }
    public static @C("long") int PIDSI_LASTAUTHOR() {
        return processenv_h$constants$112.PIDSI_LASTAUTHOR();
    }
    public static @C("long") int PIDSI_REVNUMBER() {
        return processenv_h$constants$112.PIDSI_REVNUMBER();
    }
    public static @C("long") int PIDSI_EDITTIME() {
        return processenv_h$constants$112.PIDSI_EDITTIME();
    }
    public static @C("long") int PIDSI_LASTPRINTED() {
        return processenv_h$constants$112.PIDSI_LASTPRINTED();
    }
    public static @C("long") int PIDSI_CREATE_DTM() {
        return processenv_h$constants$112.PIDSI_CREATE_DTM();
    }
    public static @C("long") int PIDSI_LASTSAVE_DTM() {
        return processenv_h$constants$112.PIDSI_LASTSAVE_DTM();
    }
    public static @C("long") int PIDSI_PAGECOUNT() {
        return processenv_h$constants$112.PIDSI_PAGECOUNT();
    }
    public static @C("long") int PIDSI_WORDCOUNT() {
        return processenv_h$constants$112.PIDSI_WORDCOUNT();
    }
    public static @C("long") int PIDSI_CHARCOUNT() {
        return processenv_h$constants$112.PIDSI_CHARCOUNT();
    }
    public static @C("long") int PIDSI_THUMBNAIL() {
        return processenv_h$constants$112.PIDSI_THUMBNAIL();
    }
    public static @C("long") int PIDSI_APPNAME() {
        return processenv_h$constants$112.PIDSI_APPNAME();
    }
    public static @C("long") int PIDSI_DOC_SECURITY() {
        return processenv_h$constants$112.PIDSI_DOC_SECURITY();
    }
    public static @C("long") int PIDMSI_EDITOR() {
        return processenv_h$constants$112.PIDMSI_EDITOR();
    }
    public static @C("long") int PIDMSI_SUPPLIER() {
        return processenv_h$constants$112.PIDMSI_SUPPLIER();
    }
    public static @C("long") int PIDMSI_SOURCE() {
        return processenv_h$constants$112.PIDMSI_SOURCE();
    }
    public static @C("long") int PIDMSI_SEQUENCE_NO() {
        return processenv_h$constants$112.PIDMSI_SEQUENCE_NO();
    }
    public static @C("long") int PIDMSI_PROJECT() {
        return processenv_h$constants$112.PIDMSI_PROJECT();
    }
    public static @C("long") int PIDMSI_STATUS() {
        return processenv_h$constants$112.PIDMSI_STATUS();
    }
    public static @C("long") int PIDMSI_OWNER() {
        return processenv_h$constants$112.PIDMSI_OWNER();
    }
    public static @C("long") int PIDMSI_RATING() {
        return processenv_h$constants$112.PIDMSI_RATING();
    }
    public static @C("long") int PIDMSI_PRODUCTION() {
        return processenv_h$constants$112.PIDMSI_PRODUCTION();
    }
    public static @C("long") int PIDMSI_COPYRIGHT() {
        return processenv_h$constants$112.PIDMSI_COPYRIGHT();
    }
    public static @C("unsigned long") int VAR_TIMEVALUEONLY() {
        return processenv_h$constants$112.VAR_TIMEVALUEONLY();
    }
    public static @C("unsigned long") int VAR_DATEVALUEONLY() {
        return processenv_h$constants$112.VAR_DATEVALUEONLY();
    }
    public static @C("unsigned long") int VAR_VALIDDATE() {
        return processenv_h$constants$112.VAR_VALIDDATE();
    }
    public static @C("unsigned long") int VAR_CALENDAR_HIJRI() {
        return processenv_h$constants$112.VAR_CALENDAR_HIJRI();
    }
    public static @C("unsigned long") int VAR_LOCALBOOL() {
        return processenv_h$constants$112.VAR_LOCALBOOL();
    }
    public static @C("unsigned long") int VAR_FORMAT_NOSUBSTITUTE() {
        return processenv_h$constants$112.VAR_FORMAT_NOSUBSTITUTE();
    }
    public static @C("unsigned long") int VAR_FOURDIGITYEARS() {
        return processenv_h$constants$112.VAR_FOURDIGITYEARS();
    }
    public static @C("unsigned long") int VAR_CALENDAR_THAI() {
        return processenv_h$constants$112.VAR_CALENDAR_THAI();
    }
    public static @C("unsigned long") int VAR_CALENDAR_GREGORIAN() {
        return processenv_h$constants$112.VAR_CALENDAR_GREGORIAN();
    }
    public static @C("int") int VTDATEGRE_MIN() {
        return processenv_h$constants$112.VTDATEGRE_MIN();
    }
    public static @C("int") int VTBIT_I1() {
        return processenv_h$constants$112.VTBIT_I1();
    }
    public static @C("int") int VTBIT_UI1() {
        return processenv_h$constants$112.VTBIT_UI1();
    }
    public static @C("int") int VTBIT_I2() {
        return processenv_h$constants$112.VTBIT_I2();
    }
    public static @C("int") int VTBIT_UI2() {
        return processenv_h$constants$112.VTBIT_UI2();
    }
    public static @C("int") int VTBIT_I4() {
        return processenv_h$constants$112.VTBIT_I4();
    }
    public static @C("int") int VTBIT_UI4() {
        return processenv_h$constants$112.VTBIT_UI4();
    }
    public static @C("int") int VTBIT_I8() {
        return processenv_h$constants$112.VTBIT_I8();
    }
    public static @C("int") int VTBIT_UI8() {
        return processenv_h$constants$112.VTBIT_UI8();
    }
    public static @C("int") int VTBIT_R4() {
        return processenv_h$constants$112.VTBIT_R4();
    }
    public static @C("int") int VTBIT_R8() {
        return processenv_h$constants$112.VTBIT_R8();
    }
    public static @C("int") int VTBIT_CY() {
        return processenv_h$constants$112.VTBIT_CY();
    }
    public static @C("int") int VTBIT_DECIMAL() {
        return processenv_h$constants$112.VTBIT_DECIMAL();
    }
    public static @C("int") int VT_HARDTYPE() {
        return processenv_h$constants$112.VT_HARDTYPE();
    }
    public static @C("int") int MEMBERID_NIL() {
        return processenv_h$constants$112.MEMBERID_NIL();
    }
    public static @C("int") int ID_DEFAULTINST() {
        return processenv_h$constants$112.ID_DEFAULTINST();
    }
    public static @C("int") int MASK_TO_RESET_TLB_BITS() {
        return processenv_h$constants$112.MASK_TO_RESET_TLB_BITS();
    }
    public static @C("long") int E_DRAW() {
        return processenv_h$constants$112.E_DRAW();
    }
    public static @C("long") int DATA_E_FORMATETC() {
        return processenv_h$constants$112.DATA_E_FORMATETC();
    }
    public static @C("long") int OLEIVERB_PRIMARY() {
        return processenv_h$constants$112.OLEIVERB_PRIMARY();
    }
    public static @C("long") int OLEIVERB_SHOW() {
        return processenv_h$constants$112.OLEIVERB_SHOW();
    }
    public static @C("long") int OLEIVERB_OPEN() {
        return processenv_h$constants$112.OLEIVERB_OPEN();
    }
    public static @C("long") int OLEIVERB_HIDE() {
        return processenv_h$constants$112.OLEIVERB_HIDE();
    }
    public static @C("long") int OLEIVERB_UIACTIVATE() {
        return processenv_h$constants$112.OLEIVERB_UIACTIVATE();
    }
    public static @C("long") int OLEIVERB_INPLACEACTIVATE() {
        return processenv_h$constants$112.OLEIVERB_INPLACEACTIVATE();
    }
    public static @C("long") int OLEIVERB_DISCARDUNDOSTATE() {
        return processenv_h$constants$112.OLEIVERB_DISCARDUNDOSTATE();
    }
    public static @C("long") int EMBDHLP_INPROC_HANDLER() {
        return processenv_h$constants$112.EMBDHLP_INPROC_HANDLER();
    }
    public static @C("long") int EMBDHLP_INPROC_SERVER() {
        return processenv_h$constants$112.EMBDHLP_INPROC_SERVER();
    }
    public static @C("long") int EMBDHLP_CREATENOW() {
        return processenv_h$constants$112.EMBDHLP_CREATENOW();
    }
    public static @C("long") int EMBDHLP_DELAYCREATE() {
        return processenv_h$constants$112.EMBDHLP_DELAYCREATE();
    }
    public static @C("unsigned long long") long OPENFILENAME_SIZE_VERSION_400A() {
        return processenv_h$constants$112.OPENFILENAME_SIZE_VERSION_400A();
    }
    public static @C("unsigned long long") long OPENFILENAME_SIZE_VERSION_400W() {
        return processenv_h$constants$112.OPENFILENAME_SIZE_VERSION_400W();
    }
    public static @C("unsigned long long") long OPENFILENAME_SIZE_VERSION_400() {
        return processenv_h$constants$112.OPENFILENAME_SIZE_VERSION_400();
    }
    public static @C("unsigned int") int CDN_FIRST() {
        return processenv_h$constants$112.CDN_FIRST();
    }
    public static @C("unsigned int") int CDN_LAST() {
        return processenv_h$constants$112.CDN_LAST();
    }
    public static @C("unsigned int") int CDN_INITDONE() {
        return processenv_h$constants$112.CDN_INITDONE();
    }
    public static @C("unsigned int") int CDN_SELCHANGE() {
        return processenv_h$constants$112.CDN_SELCHANGE();
    }
    public static @C("unsigned int") int CDN_FOLDERCHANGE() {
        return processenv_h$constants$112.CDN_FOLDERCHANGE();
    }
    public static @C("unsigned int") int CDN_SHAREVIOLATION() {
        return processenv_h$constants$112.CDN_SHAREVIOLATION();
    }
    public static @C("unsigned int") int CDN_HELP() {
        return processenv_h$constants$112.CDN_HELP();
    }
    public static @C("unsigned int") int CDN_FILEOK() {
        return processenv_h$constants$112.CDN_FILEOK();
    }
    public static @C("unsigned int") int CDN_TYPECHANGE() {
        return processenv_h$constants$112.CDN_TYPECHANGE();
    }
    public static @C("unsigned int") int CDN_INCLUDEITEM() {
        return processenv_h$constants$112.CDN_INCLUDEITEM();
    }
    public static @C("int") int CDM_FIRST() {
        return processenv_h$constants$112.CDM_FIRST();
    }
    public static @C("int") int CDM_LAST() {
        return processenv_h$constants$112.CDM_LAST();
    }
    public static @C("int") int CDM_GETSPEC() {
        return processenv_h$constants$112.CDM_GETSPEC();
    }
    public static @C("int") int CDM_GETFILEPATH() {
        return processenv_h$constants$112.CDM_GETFILEPATH();
    }
    public static @C("int") int CDM_GETFOLDERPATH() {
        return processenv_h$constants$112.CDM_GETFOLDERPATH();
    }
    public static @C("int") int CDM_GETFOLDERIDLIST() {
        return processenv_h$constants$112.CDM_GETFOLDERIDLIST();
    }
    public static @C("int") int CDM_SETCONTROLTEXT() {
        return processenv_h$constants$112.CDM_SETCONTROLTEXT();
    }
    public static @C("int") int CDM_HIDECONTROL() {
        return processenv_h$constants$112.CDM_HIDECONTROL();
    }
    public static @C("int") int CDM_SETDEFEXT() {
        return processenv_h$constants$112.CDM_SETDEFEXT();
    }
    public static @C("unsigned int") int FR_MATCHALEFHAMZA() {
        return processenv_h$constants$112.FR_MATCHALEFHAMZA();
    }
    public static @C("int") int FRM_FIRST() {
        return processenv_h$constants$112.FRM_FIRST();
    }
    public static @C("int") int FRM_LAST() {
        return processenv_h$constants$112.FRM_LAST();
    }
    public static @C("int") int FRM_SETOPERATIONRESULT() {
        return processenv_h$constants$112.FRM_SETOPERATIONRESULT();
    }
    public static @C("int") int FRM_SETOPERATIONRESULTTEXT() {
        return processenv_h$constants$112.FRM_SETOPERATIONRESULTTEXT();
    }
    public static @C("int") int CF_BOTH() {
        return processenv_h$constants$112.CF_BOTH();
    }
    public static @C("long") int CF_SHOWHELP() {
        return processenv_h$constants$112.CF_SHOWHELP();
    }
    public static @C("long") int CF_ENABLEHOOK() {
        return processenv_h$constants$112.CF_ENABLEHOOK();
    }
    public static @C("long") int CF_ENABLETEMPLATE() {
        return processenv_h$constants$112.CF_ENABLETEMPLATE();
    }
    public static @C("long") int CF_ENABLETEMPLATEHANDLE() {
        return processenv_h$constants$112.CF_ENABLETEMPLATEHANDLE();
    }
    public static @C("long") int CF_INITTOLOGFONTSTRUCT() {
        return processenv_h$constants$112.CF_INITTOLOGFONTSTRUCT();
    }
    public static @C("long") int CF_USESTYLE() {
        return processenv_h$constants$112.CF_USESTYLE();
    }
    public static @C("long") int CF_EFFECTS() {
        return processenv_h$constants$112.CF_EFFECTS();
    }
    public static @C("long") int CF_APPLY() {
        return processenv_h$constants$112.CF_APPLY();
    }
    public static @C("long") int CF_ANSIONLY() {
        return processenv_h$constants$112.CF_ANSIONLY();
    }
    public static @C("long") int CF_SCRIPTSONLY() {
        return processenv_h$constants$112.CF_SCRIPTSONLY();
    }
    public static @C("long") int CF_NOVECTORFONTS() {
        return processenv_h$constants$112.CF_NOVECTORFONTS();
    }
    public static @C("long") int CF_NOOEMFONTS() {
        return processenv_h$constants$112.CF_NOOEMFONTS();
    }
    public static @C("long") int CF_NOSIMULATIONS() {
        return processenv_h$constants$112.CF_NOSIMULATIONS();
    }
    public static @C("long") int CF_LIMITSIZE() {
        return processenv_h$constants$112.CF_LIMITSIZE();
    }
    public static @C("long") int CF_FIXEDPITCHONLY() {
        return processenv_h$constants$112.CF_FIXEDPITCHONLY();
    }
    public static @C("long") int CF_WYSIWYG() {
        return processenv_h$constants$112.CF_WYSIWYG();
    }
    public static @C("long") int CF_FORCEFONTEXIST() {
        return processenv_h$constants$112.CF_FORCEFONTEXIST();
    }
    public static @C("long") int CF_SCALABLEONLY() {
        return processenv_h$constants$112.CF_SCALABLEONLY();
    }
    public static @C("long") int CF_TTONLY() {
        return processenv_h$constants$112.CF_TTONLY();
    }
    public static @C("long") int CF_NOFACESEL() {
        return processenv_h$constants$112.CF_NOFACESEL();
    }
    public static @C("long") int CF_NOSTYLESEL() {
        return processenv_h$constants$112.CF_NOSTYLESEL();
    }
    public static @C("long") int CF_NOSIZESEL() {
        return processenv_h$constants$112.CF_NOSIZESEL();
    }
    public static @C("long") int CF_SELECTSCRIPT() {
        return processenv_h$constants$112.CF_SELECTSCRIPT();
    }
    public static @C("long") int CF_NOSCRIPTSEL() {
        return processenv_h$constants$112.CF_NOSCRIPTSEL();
    }
    public static @C("long") int CF_NOVERTFONTS() {
        return processenv_h$constants$112.CF_NOVERTFONTS();
    }
    public static @C("long") int CF_INACTIVEFONTS() {
        return processenv_h$constants$112.CF_INACTIVEFONTS();
    }
    public static @C("int") int WM_CHOOSEFONT_GETLOGFONT() {
        return processenv_h$constants$112.WM_CHOOSEFONT_GETLOGFONT();
    }
    public static @C("int") int WM_CHOOSEFONT_SETLOGFONT() {
        return processenv_h$constants$112.WM_CHOOSEFONT_SETLOGFONT();
    }
    public static @C("int") int WM_CHOOSEFONT_SETFLAGS() {
        return processenv_h$constants$112.WM_CHOOSEFONT_SETFLAGS();
    }
    public static @C("char*") MemorySegment LBSELCHSTRINGA() {
        return processenv_h$constants$112.LBSELCHSTRINGA();
    }
    public static @C("char*") MemorySegment SHAREVISTRINGA() {
        return processenv_h$constants$112.SHAREVISTRINGA();
    }
    public static @C("char*") MemorySegment FILEOKSTRINGA() {
        return processenv_h$constants$112.FILEOKSTRINGA();
    }
    public static @C("char*") MemorySegment COLOROKSTRINGA() {
        return processenv_h$constants$112.COLOROKSTRINGA();
    }
    public static @C("char*") MemorySegment SETRGBSTRINGA() {
        return processenv_h$constants$112.SETRGBSTRINGA();
    }
    public static @C("char*") MemorySegment HELPMSGSTRINGA() {
        return processenv_h$constants$112.HELPMSGSTRINGA();
    }
    public static @C("char*") MemorySegment FINDMSGSTRINGA() {
        return processenv_h$constants$112.FINDMSGSTRINGA();
    }
    public static @C("unsigned short*") MemorySegment LBSELCHSTRINGW() {
        return processenv_h$constants$112.LBSELCHSTRINGW();
    }
    public static @C("unsigned short*") MemorySegment SHAREVISTRINGW() {
        return processenv_h$constants$112.SHAREVISTRINGW();
    }
    public static @C("unsigned short*") MemorySegment FILEOKSTRINGW() {
        return processenv_h$constants$112.FILEOKSTRINGW();
    }
    public static @C("unsigned short*") MemorySegment COLOROKSTRINGW() {
        return processenv_h$constants$112.COLOROKSTRINGW();
    }
    public static @C("unsigned short*") MemorySegment SETRGBSTRINGW() {
        return processenv_h$constants$112.SETRGBSTRINGW();
    }
    public static @C("unsigned short*") MemorySegment HELPMSGSTRINGW() {
        return processenv_h$constants$112.HELPMSGSTRINGW();
    }
    public static @C("unsigned short*") MemorySegment FINDMSGSTRINGW() {
        return processenv_h$constants$112.FINDMSGSTRINGW();
    }
    public static @C("char*") MemorySegment LBSELCHSTRING() {
        return processenv_h$constants$112.LBSELCHSTRING();
    }
    public static @C("char*") MemorySegment SHAREVISTRING() {
        return processenv_h$constants$112.SHAREVISTRING();
    }
    public static @C("char*") MemorySegment FILEOKSTRING() {
        return processenv_h$constants$112.FILEOKSTRING();
    }
    public static @C("char*") MemorySegment COLOROKSTRING() {
        return processenv_h$constants$112.COLOROKSTRING();
    }
    public static @C("char*") MemorySegment SETRGBSTRING() {
        return processenv_h$constants$112.SETRGBSTRING();
    }
    public static @C("char*") MemorySegment HELPMSGSTRING() {
        return processenv_h$constants$112.HELPMSGSTRING();
    }
    public static @C("char*") MemorySegment FINDMSGSTRING() {
        return processenv_h$constants$112.FINDMSGSTRING();
    }
    public static @C("int") int CD_LBSELNOITEMS() {
        return processenv_h$constants$112.CD_LBSELNOITEMS();
    }
    public static @C("long") int PD_EXCL_COPIESANDCOLLATE() {
        return processenv_h$constants$112.PD_EXCL_COPIESANDCOLLATE();
    }
    public static @C("unsigned int") int START_PAGE_GENERAL() {
        return processenv_h$constants$112.START_PAGE_GENERAL();
    }
    public static @C("int") int WM_PSD_PAGESETUPDLG() {
        return processenv_h$constants$112.WM_PSD_PAGESETUPDLG();
    }
    public static @C("int") int WM_PSD_FULLPAGERECT() {
        return processenv_h$constants$112.WM_PSD_FULLPAGERECT();
    }
    public static @C("int") int WM_PSD_MINMARGINRECT() {
        return processenv_h$constants$112.WM_PSD_MINMARGINRECT();
    }
    public static @C("int") int WM_PSD_MARGINRECT() {
        return processenv_h$constants$112.WM_PSD_MARGINRECT();
    }
    public static @C("int") int WM_PSD_GREEKTEXTRECT() {
        return processenv_h$constants$112.WM_PSD_GREEKTEXTRECT();
    }
    public static @C("int") int WM_PSD_ENVSTAMPRECT() {
        return processenv_h$constants$112.WM_PSD_ENVSTAMPRECT();
    }
    public static @C("int") int WM_PSD_YAFULLPAGERECT() {
        return processenv_h$constants$112.WM_PSD_YAFULLPAGERECT();
    }
    public static @C("unsigned short*") MemorySegment SERVICES_ACTIVE_DATABASEW() {
        return processenv_h$constants$112.SERVICES_ACTIVE_DATABASEW();
    }
    public static @C("unsigned short*") MemorySegment SERVICES_FAILED_DATABASEW() {
        return processenv_h$constants$112.SERVICES_FAILED_DATABASEW();
    }
    public static @C("char*") MemorySegment SERVICES_ACTIVE_DATABASEA() {
        return processenv_h$constants$112.SERVICES_ACTIVE_DATABASEA();
    }
    public static @C("char*") MemorySegment SERVICES_FAILED_DATABASEA() {
        return processenv_h$constants$112.SERVICES_FAILED_DATABASEA();
    }
    public static @C("unsigned short") short SC_GROUP_IDENTIFIERW() {
        return processenv_h$constants$112.SC_GROUP_IDENTIFIERW();
    }
    public static @C("int") int SC_GROUP_IDENTIFIERA() {
        return processenv_h$constants$112.SC_GROUP_IDENTIFIERA();
    }
    public static @C("char*") MemorySegment SERVICES_ACTIVE_DATABASE() {
        return processenv_h$constants$112.SERVICES_ACTIVE_DATABASE();
    }
    public static @C("char*") MemorySegment SERVICES_FAILED_DATABASE() {
        return processenv_h$constants$112.SERVICES_FAILED_DATABASE();
    }
    public static @C("int") int SC_GROUP_IDENTIFIER() {
        return processenv_h$constants$112.SC_GROUP_IDENTIFIER();
    }
    public static @C("unsigned int") int SERVICE_NO_CHANGE() {
        return processenv_h$constants$112.SERVICE_NO_CHANGE();
    }
    public static @C("int") int SERVICE_STATE_ALL() {
        return processenv_h$constants$112.SERVICE_STATE_ALL();
    }
    public static @C("long") int SC_MANAGER_ALL_ACCESS() {
        return processenv_h$constants$112.SC_MANAGER_ALL_ACCESS();
    }
    public static @C("long") int SERVICE_ALL_ACCESS() {
        return processenv_h$constants$112.SERVICE_ALL_ACCESS();
    }
    public static @C("int") int SERVICE_NOTIFY_STATUS_CHANGE() {
        return processenv_h$constants$112.SERVICE_NOTIFY_STATUS_CHANGE();
    }
    public static @C("unsigned int") int SERVICE_STOP_REASON_FLAG_MAX() {
        return processenv_h$constants$112.SERVICE_STOP_REASON_FLAG_MAX();
    }
    public static @C("int") int SERVICE_SID_TYPE_RESTRICTED() {
        return processenv_h$constants$112.SERVICE_SID_TYPE_RESTRICTED();
    }
    public static @C("unsigned short*") MemorySegment SERVICE_TRIGGER_STARTED_ARGUMENT() {
        return processenv_h$constants$112.SERVICE_TRIGGER_STARTED_ARGUMENT();
    }
    public static @C("unsigned short*") MemorySegment SC_AGGREGATE_STORAGE_KEY() {
        return processenv_h$constants$112.SC_AGGREGATE_STORAGE_KEY();
    }
    public static @C("int") int MDM_MASK_PROTOCOLINFO() {
        return processenv_h$constants$112.MDM_MASK_PROTOCOLINFO();
    }
    public static @C("int") int MDM_SHIFT_PROTOCOLINFO() {
        return processenv_h$constants$112.MDM_SHIFT_PROTOCOLINFO();
    }
    public static @C("int") int MDM_MASK_EXTENDEDINFO() {
        return processenv_h$constants$112.MDM_MASK_EXTENDEDINFO();
    }
    public static @C("int") int MDM_SHIFT_EXTENDEDINFO() {
        return processenv_h$constants$112.MDM_SHIFT_EXTENDEDINFO();
    }
    public static @C("int") int MDM_MASK_HDLCPPP_AUTH() {
        return processenv_h$constants$112.MDM_MASK_HDLCPPP_AUTH();
    }
    public static @C("int") int MDM_MASK_HDLCPPP_ML() {
        return processenv_h$constants$112.MDM_MASK_HDLCPPP_ML();
    }
    public static @C("int") int MDM_PROTOCOL_HDLCPPP_64K() {
        return processenv_h$constants$112.MDM_PROTOCOL_HDLCPPP_64K();
    }
    public static @C("int") int MDM_PROTOCOL_HDLCPPP_56K() {
        return processenv_h$constants$112.MDM_PROTOCOL_HDLCPPP_56K();
    }
    public static @C("int") int MDM_PROTOCOL_HDLCPPP_112K() {
        return processenv_h$constants$112.MDM_PROTOCOL_HDLCPPP_112K();
    }
    public static @C("int") int MDM_PROTOCOL_HDLCPPP_112K_PAP() {
        return processenv_h$constants$112.MDM_PROTOCOL_HDLCPPP_112K_PAP();
    }
    public static @C("int") int MDM_PROTOCOL_HDLCPPP_112K_CHAP() {
        return processenv_h$constants$112.MDM_PROTOCOL_HDLCPPP_112K_CHAP();
    }
    public static @C("int") int MDM_PROTOCOL_HDLCPPP_112K_MSCHAP() {
        return processenv_h$constants$112.MDM_PROTOCOL_HDLCPPP_112K_MSCHAP();
    }
    public static @C("int") int MDM_PROTOCOL_HDLCPPP_128K() {
        return processenv_h$constants$112.MDM_PROTOCOL_HDLCPPP_128K();
    }
    public static @C("int") int MDM_PROTOCOL_HDLCPPP_128K_PAP() {
        return processenv_h$constants$112.MDM_PROTOCOL_HDLCPPP_128K_PAP();
    }
    public static @C("int") int MDM_PROTOCOL_HDLCPPP_128K_CHAP() {
        return processenv_h$constants$112.MDM_PROTOCOL_HDLCPPP_128K_CHAP();
    }
    public static @C("int") int MDM_PROTOCOL_HDLCPPP_128K_MSCHAP() {
        return processenv_h$constants$112.MDM_PROTOCOL_HDLCPPP_128K_MSCHAP();
    }
    public static @C("int") int MDM_MASK_V120_ML() {
        return processenv_h$constants$112.MDM_MASK_V120_ML();
    }
    public static @C("int") int MDM_PROTOCOL_V120_64K() {
        return processenv_h$constants$112.MDM_PROTOCOL_V120_64K();
    }
    public static @C("int") int MDM_PROTOCOL_V120_56K() {
        return processenv_h$constants$112.MDM_PROTOCOL_V120_56K();
    }
    public static @C("int") int MDM_PROTOCOL_V120_112K() {
        return processenv_h$constants$112.MDM_PROTOCOL_V120_112K();
    }
    public static @C("int") int MDM_PROTOCOL_V120_128K() {
        return processenv_h$constants$112.MDM_PROTOCOL_V120_128K();
    }
    public static @C("int") int MDM_PROTOCOL_X75_64K() {
        return processenv_h$constants$112.MDM_PROTOCOL_X75_64K();
    }
    public static @C("int") int MDM_PROTOCOL_X75_128K() {
        return processenv_h$constants$112.MDM_PROTOCOL_X75_128K();
    }
    public static @C("int") int MDM_PROTOCOL_X75_T_70() {
        return processenv_h$constants$112.MDM_PROTOCOL_X75_T_70();
    }
    public static @C("int") int MDM_PROTOCOL_X75_BTX() {
        return processenv_h$constants$112.MDM_PROTOCOL_X75_BTX();
    }
    public static @C("int") int MDM_PROTOCOL_V110_1DOT2K() {
        return processenv_h$constants$112.MDM_PROTOCOL_V110_1DOT2K();
    }
    public static @C("int") int MDM_PROTOCOL_V110_2DOT4K() {
        return processenv_h$constants$112.MDM_PROTOCOL_V110_2DOT4K();
    }
    public static @C("int") int MDM_PROTOCOL_V110_4DOT8K() {
        return processenv_h$constants$112.MDM_PROTOCOL_V110_4DOT8K();
    }
    public static @C("int") int MDM_PROTOCOL_V110_9DOT6K() {
        return processenv_h$constants$112.MDM_PROTOCOL_V110_9DOT6K();
    }
    public static @C("int") int MDM_PROTOCOL_V110_12DOT0K() {
        return processenv_h$constants$112.MDM_PROTOCOL_V110_12DOT0K();
    }
    public static @C("int") int MDM_PROTOCOL_V110_14DOT4K() {
        return processenv_h$constants$112.MDM_PROTOCOL_V110_14DOT4K();
    }
    public static @C("int") int MDM_PROTOCOL_V110_19DOT2K() {
        return processenv_h$constants$112.MDM_PROTOCOL_V110_19DOT2K();
    }
    public static @C("int") int MDM_PROTOCOL_V110_28DOT8K() {
        return processenv_h$constants$112.MDM_PROTOCOL_V110_28DOT8K();
    }
    public static @C("int") int MDM_PROTOCOL_V110_38DOT4K() {
        return processenv_h$constants$112.MDM_PROTOCOL_V110_38DOT4K();
    }
    public static @C("int") int MDM_PROTOCOL_V110_57DOT6K() {
        return processenv_h$constants$112.MDM_PROTOCOL_V110_57DOT6K();
    }
    public static @C("int") int MDM_MASK_AUTO_ML() {
        return processenv_h$constants$112.MDM_MASK_AUTO_ML();
    }
    public static @C("int") int MDM_PROTOCOL_AUTO_1CH() {
        return processenv_h$constants$112.MDM_PROTOCOL_AUTO_1CH();
    }
    public static @C("int") int MDM_PROTOCOL_AUTO_2CH() {
        return processenv_h$constants$112.MDM_PROTOCOL_AUTO_2CH();
    }
    public static @C("int") int MDM_PROTOCOL_ANALOG_RLP() {
        return processenv_h$constants$112.MDM_PROTOCOL_ANALOG_RLP();
    }
    public static @C("int") int MDM_PROTOCOL_ANALOG_NRLP() {
        return processenv_h$constants$112.MDM_PROTOCOL_ANALOG_NRLP();
    }
    public static @C("int") int MDM_PROTOCOL_ANALOG_V34() {
        return processenv_h$constants$112.MDM_PROTOCOL_ANALOG_V34();
    }
    public static @C("int") int MDM_PROTOCOL_GPRS() {
        return processenv_h$constants$112.MDM_PROTOCOL_GPRS();
    }
    public static @C("int") int MDM_PROTOCOL_PIAFS_INCOMING() {
        return processenv_h$constants$112.MDM_PROTOCOL_PIAFS_INCOMING();
    }
    public static @C("int") int MDM_PROTOCOL_PIAFS_OUTGOING() {
        return processenv_h$constants$112.MDM_PROTOCOL_PIAFS_OUTGOING();
    }
    public static @C("unsigned int") int ISC_SHOWUICOMPOSITIONWINDOW() {
        return processenv_h$constants$112.ISC_SHOWUICOMPOSITIONWINDOW();
    }
    public static @C("unsigned int") int ISC_SHOWUIALL() {
        return processenv_h$constants$112.ISC_SHOWUIALL();
    }
    public static @C("unsigned long") int IGP_GETIMEVERSION() {
        return processenv_h$constants$112.IGP_GETIMEVERSION();
    }
    public static @C("int") int SCS_SETSTR() {
        return processenv_h$constants$112.SCS_SETSTR();
    }
    public static @C("int") int SCS_CHANGEATTR() {
        return processenv_h$constants$112.SCS_CHANGEATTR();
    }
    public static @C("int") int SCS_CHANGECLAUSE() {
        return processenv_h$constants$112.SCS_CHANGECLAUSE();
    }
    public static @C("int") int IME_CMODE_CHINESE() {
        return processenv_h$constants$112.IME_CMODE_CHINESE();
    }
    public static @C("int") int IME_CMODE_HANGUL() {
        return processenv_h$constants$112.IME_CMODE_HANGUL();
    }
    public static @C("int") int IME_CMODE_JAPANESE() {
        return processenv_h$constants$112.IME_CMODE_JAPANESE();
    }
    public static @C("int") int IME_CMODE_HANGEUL() {
        return processenv_h$constants$112.IME_CMODE_HANGEUL();
    }
    public static @C("unsigned int") int IME_CMODE_RESERVED() {
        return processenv_h$constants$112.IME_CMODE_RESERVED();
    }
    public static @C("int") int IMM_ERROR_NODATA() {
        return processenv_h$constants$112.IMM_ERROR_NODATA();
    }
    public static @C("int") int IMM_ERROR_GENERAL() {
        return processenv_h$constants$112.IMM_ERROR_GENERAL();
    }
    public static @C("unsigned int") int IME_REGWORD_STYLE_USER_FIRST() {
        return processenv_h$constants$112.IME_REGWORD_STYLE_USER_FIRST();
    }
    public static @C("unsigned int") int IME_REGWORD_STYLE_USER_LAST() {
        return processenv_h$constants$112.IME_REGWORD_STYLE_USER_LAST();
    }
    public static @C("long") int IMFS_GRAYED() {
        return processenv_h$constants$112.IMFS_GRAYED();
    }
    public static @C("long") int IMFS_DISABLED() {
        return processenv_h$constants$112.IMFS_DISABLED();
    }
    public static @C("long") int IMFS_CHECKED() {
        return processenv_h$constants$112.IMFS_CHECKED();
    }
    public static @C("long") int IMFS_HILITE() {
        return processenv_h$constants$112.IMFS_HILITE();
    }
    public static @C("long") int IMFS_ENABLED() {
        return processenv_h$constants$112.IMFS_ENABLED();
    }
    public static @C("long") int IMFS_UNCHECKED() {
        return processenv_h$constants$112.IMFS_UNCHECKED();
    }
    public static @C("long") int IMFS_UNHILITE() {
        return processenv_h$constants$112.IMFS_UNHILITE();
    }
    public static @C("long") int IMFS_DEFAULT() {
        return processenv_h$constants$112.IMFS_DEFAULT();
    }
}


