// Generated by jextract

package com.github.tornaia.cf.win.processenv;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import jdk.incubator.foreign.*;
import jdk.incubator.foreign.MemoryLayout.PathElement;
import static jdk.incubator.foreign.CLinker.*;
class processenv_h$constants$144 extends processenv_h$constants$143 {

    /* package-private */ processenv_h$constants$144() {}
}

