// Generated by jextract

package com.github.tornaia.cf.win.sysinfoapi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import jdk.incubator.foreign.*;
import jdk.incubator.foreign.MemoryLayout.PathElement;
import static jdk.incubator.foreign.CLinker.*;
class sysinfoapi_h$constants$140 extends sysinfoapi_h$constants$139 {

    /* package-private */ sysinfoapi_h$constants$140() {}
}

