// Generated by jextract

package com.github.tornaia.cf.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import jdk.incubator.foreign.*;
import jdk.incubator.foreign.MemoryLayout.PathElement;
import static jdk.incubator.foreign.CLinker.*;
class sysinfoapi_h$constants$152 extends sysinfoapi_h$constants$151 {

    /* package-private */ sysinfoapi_h$constants$152() {}
}

