// Generated by jextract

package com.github.tornaia.cf.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import jdk.incubator.foreign.*;
import jdk.incubator.foreign.MemoryLayout.PathElement;
import static jdk.incubator.foreign.CLinker.*;
class Windows_h$constants$144 extends Windows_h$constants$143 {

    /* package-private */ Windows_h$constants$144() {}
}

