// Generated by jextract

package com.github.tornaia.cf.win.cfapi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import jdk.incubator.foreign.*;
import jdk.incubator.foreign.MemoryLayout.PathElement;
import static jdk.incubator.foreign.CLinker.*;
class Windows_h$constants$142 extends Windows_h$constants$141 {

    /* package-private */ Windows_h$constants$142() {}
}

